---
- name: Install certbot dependencies
  apt:
    state: present
    name: software-properties-common

- name: Add certbot PPA repository for 18.04
  apt_repository:
    state: present
    repo: ppa:certbot/certbot
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "18"

- name: Install 'certbot'
  apt:
    state: present
    name: certbot
