---
- name: Unzip Android Studio to /opt
  become: yes
  unarchive:
    src: "{{ home_dir }}/downloads/srv/android-studio-ide-192.6392135-linux.tar.gz"
    dest: /opt
    creates: /opt/android-studio/bin/studio.sh
    remote_src: yes

- name: Create Android SDK folder in HOME
  file:
    state: directory
    path: "{{ home_dir }}/android/sdk"
    owner: "{{ username }}"
    group: "{{ username }}"

# See: https://developer.android.com/studio/run/emulator-acceleration?utm_source=android-studio#vm-linux
- name: Install .debs to enable KVM acceleration for Android emulator
  become: yes
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - bridge-utils
    - libvirt-clients
    - libvirt-daemon-system
    - qemu-kvm
  tags:
    - pkg_install

- name: Add {{ username }} to groups required for Android emulator KVM
  become: yes
  user:
    name: "{{ username }}"
    groups:
      - kvm
      - libvirt
    append: yes

- name: Install Android Debug Bridge (adb)
  become: yes
  apt:
    state: present
    name: adb

- name: Add {{ username }} to groups required for 'adb'
  become: yes
  user:
    name: "{{ username }}"
    groups:
      - plugdev
    append: yes

- name: Download JetBrains Toolbox tarball SHA-256 checksum
  shell: |
    curl -s https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.17.6856.tar.gz.sha256 \
      | cut -d ' ' -f 1 > /tmp/jetbrains_toolbox_tar.sha256
  args:
    creates: /tmp/jetbrains_toolbox_tar.sha256
    warn: no

- name: Download JetBrains Toolbox tarball
  get_url:
    url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.17.6856.tar.gz
    dest: "{{ home_dir }}/downloads/srv/jetbrains-toolbox-1.17.6856.tar.gz"
    checksum: sha256:{{ jetbrains_toolbox_tar_sha256 }}
  vars:
    jetbrains_toolbox_tar_sha256: "{{ lookup('file', '/tmp/jetbrains_toolbox_tar.sha256') }}"

- name: Unarchive JetBrains Toolbox tarball to /opt
  become: yes
  unarchive:
    src: "{{ home_dir }}/downloads/srv/jetbrains-toolbox-1.17.6856.tar.gz"
    dest: /opt
    remote_src: yes

- name: Download Vagrant .deb SHA-256 checksum
  shell: |
    curl -s https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_SHA256SUMS \
      | grep vagrant_2.2.9_x86_64.deb \
      | cut -d ' ' -f 1 > /tmp/vagrant_deb.sha256
  args:
    creates: /tmp/vagrant_deb.sha256
    warn: no

- name: Download Vagrant .deb
  get_url:
    url: https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
    dest: "{{ home_dir }}/downloads/srv/vagrant_2.2.9_x86_64.deb"
    checksum: sha256:{{ vagrant_deb_sha256 }}
  vars:
    vagrant_deb_sha256: "{{ lookup('file', '/tmp/vagrant_deb.sha256') }}"

- name: Install Vagrant via .deb
  become: yes
  apt:
    state: present
    deb: "{{ home_dir }}/downloads/srv/vagrant_2.2.9_x86_64.deb"

- name: Download Oracle VirtualBox .deb SHA-256 checksum
  shell: |
    curl -s https://www.virtualbox.org/download/hashes/6.1.8/SHA256SUMS \
      | grep virtualbox-6.1_6.1.8-137981~Ubuntu~eoan_amd64.deb \
      | cut -d ' ' -f 1 > /tmp/virtualbox_deb.sha256
  args:
    creates: /tmp/virtualbox_deb.sha256
    warn: no

- name: Download Oracle VirtualBox .deb
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.1.8/virtualbox-6.1_6.1.8-137981~Ubuntu~eoan_amd64.deb
    dest: "{{ home_dir }}/downloads/srv/virtualbox-6.1_6.1.8-137981~Ubuntu~eoan_amd64.deb"
    checksum: sha256:{{ virtualbox_deb_sha256 }}
  vars:
    virtualbox_deb_sha256: "{{ lookup('file', '/tmp/virtualbox_deb.sha256') }}"

- name: Install Oracle VirtualBox via .deb
  become: yes
  apt:
    state: present
    deb: "{{ home_dir }}/downloads/srv/virtualbox-6.1_6.1.8-137981~Ubuntu~eoan_amd64.deb"

- name: Install Multipass Ubuntu VM manager by Canonical
  become: yes
  snap:
    state: present
    name: multipass
    classic: yes
