---
- name: Unzip Android Studio to /opt
  become: yes
  unarchive:
    src: "{{ home_dir }}/downloads/srv/android-studio-ide-192.6392135-linux.tar.gz"
    dest: /opt
    creates: /opt/android-studio/bin/studio.sh
    remote_src: yes

- name: Create Android SDK folder in HOME
  file:
    state: directory
    path: "{{ home_dir }}/android/sdk"
    owner: "{{ username }}"
    group: "{{ username }}"

# See: https://developer.android.com/studio/run/emulator-acceleration?utm_source=android-studio#vm-linux
- name: Install .debs to enable KVM acceleration for Android emulator
  become: yes
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - bridge-utils
    - libvirt-clients
    - libvirt-daemon-system
    - qemu-kvm

- name: Add {{ username }} to groups required for Android emulator KVM
  become: yes
  user:
    name: "{{ username }}"
    groups:
      - kvm
      - libvirt
    append: yes

- name: Install Android Debug Bridge (adb)
  become: yes
  apt:
    state: present
    name: adb

- name: Add {{ username }} to groups required for 'adb'
  become: yes
  user:
    name: "{{ username }}"
    groups:
      - plugdev
    append: yes

- name: Download JetBrains Toolbox tarball SHA-256 checksum
  shell: curl -s https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.17.6856.tar.gz.sha256 | cut -d ' ' -f 1
  register: jetbrains_toolbox_tarball_sha256sum
  args:
    warn: no

- name: Download JetBrains Toolbox tarball
  get_url:
    url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.17.6856.tar.gz
    dest: "{{ home_dir }}/downloads/srv/jetbrains-toolbox-1.17.6856.tar.gz"
    checksum: sha256:{{ jetbrains_toolbox_tarball_sha256sum.stdout }}

- name: Unarchive JetBrains Toolbox tarball to /opt
  unarchive:
    src: "{{ home_dir }}/downloads/srv/jetbrains-toolbox-1.17.6856.tar.gz"
    dest: /opt
    remote_src: yes
