---
#-------------------------------------------------------------------------------
# Use the following whenever Docker adds 20.04 packages to its APT repo; for
# now, we are just going to install Docker from the main Ubuntu repos.
#-------------------------------------------------------------------------------
#- name: Install Docker .deb dependencies
#  apt:
#    state: present
#    name: "{{ item }}"
#  loop:
#    - apt-transport-https
#    - ca-certificates
#    - curl
#    - gnupg-agent
#    - software-properties-common
#
#- name: Install Docker's APT repository key
#  apt_key:
#    state: present
#    url: https://download.docker.com/linux/ubuntu/gpg
#
#- name: Add Docker's APT repository
#  apt_repository:
#    state: present
#    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker from Ubuntu package repo
  become: yes
  apt:
    state: present
    name: docker.io=19.03.8-0ubuntu1

- name: Create 'docker' group
  become: yes
  group:
    state: present
    name: docker
    system: yes

- name: Add 'mmackey' to 'docker' group
  become: yes
  user:
    state: present
    name: "{{ username }}"
    append: yes
    groups:
      - docker

- name: Build 'docker-compose' URL
  shell: |
    echo "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" 
  register: docker_compose_url

- name: Download & install 'docker-compose'
  become: yes
  get_url:
    url: "{{ docker_compose_url.stdout }}"
    dest: "{{ docker_compose_bin }}"
    mode: "ugo+x"

- name: Download & install 'docker-compose' Bash completion
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.25.5/contrib/completion/bash/docker-compose
    dest: "/etc/bash_completion.d/docker-compose"
