---
#-------------------------------------------------------------------------------
# Microsoft
#-------------------------------------------------------------------------------
# There is no checksum for this pkg from MS so installing directly from URL
# without any checksum
- name: Install Microsoft APT configuration for packages.microsoft.com via .deb
  become: yes
  apt:
    state: present
    deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

# This is to ensure last steps repos & keys are picked-up by APT
#- name: Force update of APT cache
  #become: yes
  #apt:
    #update_cache: yes

# Always update cache to ensure pick-up of MS APT configuration package install
- name: Install Microsoft .NET SDK dependency
  become: yes
  apt:
    state: present
    name: apt-transport-https
    update_cache: yes

# Always update cache to enusre pick-up .NET SDK dependency install
- name: Install Microsoft .NET Core SDK
  become: yes
  apt:
    state: present
    name: dotnet-sdk-3.1
    update_cache: yes

# SEE: https://www.mono-project.com/download/stable/#download-lin-ubuntu
- name: Install Mono Runtime to run .NET applications on Linux
  become: yes
  apt:
    state: present
    name: mono-complete
