- name: Ensure '/etc/sudoers' has include for '/etc/sudoers.d'
  lineinfile:
    state: present
    line: "#includedir /etc/sudoers.d"
    dest: /etc/sudoers
    validate: "/usr/sbin/visudo -cf %s"

# See: /etc/sudoer.d/README for docs on this type of sudoers file
- name: Grant '{{ username }}' NOPASSWD sudo access
  become: yes
  copy:
    src: mmackey.sudoers
    dest: /etc/sudoers.d/mmackey
    mode: 0440
    owner: root
    group: root
