---
- name: Create '{{ username }}' user with a default SSH key
  become: yes
  user:
    state: present
    name: "{{ username }}"
    # this allows other tasks to add this user to groups; otherwise, every time
    # this task is run, it will overwrite any other groups this user has been
    # added to by other tasks
    append: yes
    comment: "{{ name }}"
    create_home: yes
    generate_ssh_key: yes
    # Default groups for the user created by Ubuntu Installer
    groups:
      - adm
      - cdrom
      - dip
      - lpadmin
      - lxd
      - plugdev
      - sambashare
      - sudo
    password: "{{ password }}"
    shell: /bin/bash
    ssh_key_bits: 4096
    ssh_key_comment: "{{ username }}-lenovo_20.04_default"
    ssh_key_file: "{{ home_dir }}/.ssh/id_rsa"
    ssh_key_passphrase: "{{ mmackey_ssh_key_passphrase }}"
    ssh_key_type: rsa

- name: Change SSH private key mode to read-only
  file:
    state: file
    path: "{{ home_dir }}/.ssh/id_rsa"
    mode: 0400
    group: "{{ username }}"
    owner: "{{ username }}"

- name: Create Github SSH key for '{{ username }}'
  become: yes
  user:
    state: present
    name: "{{ username }}"
    force: no      # keeps an existing key from being overwritten
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ username }}-lenovo_github"
    ssh_key_file: "{{ home_dir }}/.ssh/{{ username }}_github-id_rsa"
    ssh_key_passphrase: "{{ mmackey_github_ssh_key_passphrase }}"
    ssh_key_type: rsa

- name: Change Github SSH private key mode to read-only
  file:
    state: file
    path: "{{ home_dir }}/.ssh/{{ username }}_github-id_rsa"
    mode: 0400
    group: "{{ username }}"
    owner: "{{ username }}"

