---
- name: Download Vagrant .deb SHA-256 checksum
  shell: |
    curl -s https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_SHA256SUMS \
      | grep vagrant_2.2.9_x86_64.deb \
      | cut -d ' ' -f 1 > /tmp/vagrant_deb.sha256
  args:
    creates: /tmp/vagrant_deb.sha256
    warn: no

- name: Download Vagrant .deb
  get_url:
    url: https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
    dest: "{{ home_dir }}/downloads/srv/vagrant_2.2.9_x86_64.deb"
    checksum: sha256:{{ vagrant_deb_sha256 }}
  vars:
    vagrant_deb_sha256: "{{ lookup('file', '/tmp/vagrant_deb.sha256') }}"

- name: Install Vagrant via .deb
  become: yes
  apt:
    state: present
    deb: "{{ home_dir }}/downloads/srv/vagrant_2.2.9_x86_64.deb"

- name: Download Oracle VirtualBox .deb SHA-256 checksum
  shell: |
    curl -s "{{ virtualbox_hash_url }}" \
      | grep "{{ virtualbox_deb_file }}" \
      | cut -d ' ' -f 1 > "/tmp/{{ virtualbox_deb_file }}.sha256"
  args:
    creates: "/tmp/{{ virtualbox_deb_file }}.sha256"
    warn: no

- name: Download Oracle VirtualBox .deb
  get_url:
    url: "{{ virtualbox_deb_url }}"
    dest: "{{ home_dir }}/downloads/srv/{{ virtualbox_deb_file }}"
    checksum: sha256:{{ virtualbox_deb_sha256 }}
  vars:
    virtualbox_deb_sha256: "{{ lookup('file', '/tmp/' + virtualbox_deb_file + '.sha256') }}"

- name: Install Oracle VirtualBox via .deb
  become: yes
  apt:
    state: present
    deb: "{{ home_dir }}/downloads/srv/{{ virtualbox_deb_file }}"

- name: Add "{{ username }}" to 'vboxusers' group
  become: yes
  user:
    state: present
    name: "{{ username }}"
    append: yes
    groups:
      - vboxusers

- name: Install Multipass Ubuntu VM manager by Canonical
  become: yes
  snap:
    state: present
    name: multipass
    classic: yes

# Download requires website login, EULA acceptance, etc.; so is a real pain
- name: Verify checksum on Pre-Downloaded VMware ovftool installer
  shell: shasum -a 256 -c VMware-ovftool-4.4.0-16360108-lin.x86_64.bundle.shasum
  changed_when: False
  args:
    chdir: "{{ home_dir }}/downloads/srv"

- name: Run VMware ovftool installer
  become: yes
  shell: |
    ./VMware-ovftool-4.4.0-16360108-lin.x86_64.bundle \
      --console \
      --required \
      --eulas-agreed
  args:
    chdir: "{{ home_dir }}/downloads/srv"
    creates: /usr/bin/ovftool

