---
hacker_install_burp: no

#-------------------------------------------------------------------------------
# PACKAGES / SNAPS
#-------------------------------------------------------------------------------
hacker_packages_common:
  - ack-grep
  - curl
  - fd-find
  - fzf
  - git
  - htop
  - jq
  - p7zip-full
  - ripgrep
  - tmux
  - tree
  - wget
  - xclip
  - xsel

hacker_packages_tools:
  - ascii

hacker_snaps_tools:
  - amass
  - john-the-ripper

hacker_packages_pentest:
  - arping
  - arp-scan
  - iputils-ping
  - iputils-tracepath
  - mysql-client
  - net-tools
  - nikto
  - nmap
  - tshark
  - whois

hacker_snaps_pentest: []

hacker_packages_forensics:
  - binwalk
  - foremost
  - steghide

hacker_packages_reverse_engr:
  - fs-uae
  - fs-uae-launcher

hacker_snaps_classic: []

# UNUSED
hacker_packages_ctf:
  - hashcash

# UNUSED
hacker_packages_radio:
  - bluez-hcidump

# UNUSED
hacker_packages_net_gui:
  - wireshark

# UNUSED
hacker_snaps_gui:
  - postman

