- name: gitlab | reconfigure
  become: yes
  become_user: root
  shell: |
    gitlab-ctl reconfigure
  tags:
    - gitlab

- name: gitlab | restart postgres
  become: yes
  become_user: root
  # Note the name difference 'postges' vs. 'postgresql'
  shell: |
    gitlab-ctl restart postgresql
  tags:
    - gitlab
