---
# No great documentation for installing/configuring the credential helpers, but
# see here:
#   - https://github.com/docker/docker-credential-helpers/issues/102
- name: Download `docker-credential-pass` credential helper
  get_url:
    url: "https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-pass-v0.6.3-amd64.tar.gz"
    # TODO: Using home_ vs base__ b/c we don't use base role
    dest: "{{ home_downloads_dir }}/docker-credential-pass-v0.6.3-amd64.tar.gz"

# Archive only contains a single, binary file
- name: Unarchive `docker-credential-pass` binary tarball to /usr/local
  become: yes
  unarchive:
    # TODO: Using home_ vs base__ b/c we don't use base role
    src: "{{ home_downloads_dir }}/docker-credential-pass-v0.6.3-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
  args:
    creates: /usr/local/bin/docker-credential-pass

- name: Set `docker-credential-pass` to be executable & proper user/group
  become: yes
  file:
    path: /usr/local/bin/docker-credential-pass
    owner: root
    group: root
    mode: "0755"
