# No great documentation for installing/configuring the credential helpers, but
# see here:
#   - https://github.com/docker/docker-credential-helpers/issues/102
- name: Download `docker-credential-pass` credential helper
  become: yes
  become_user: root
  get_url:
    url: "{{ docker_credentials_helper__download_url }}"
    dest: /usr/local/bin/docker-credential-pass
    owner: root
    group: root
    mode: "0755"
