# TODO: clean-up this role and put vars into defaults
- name: sops | Install from remote .deb
  include_role:
    name: packages
    tasks_from: install_remote_deb.yml
  vars:
    pkg_deb_name: "{{ item.name }}"
    pkg_deb_url: "{{ item.url }}"
    pkg_deb_filename: "{{ item.filename }}"
    pkg_deb_checksum: "{{ item.checksum | default('') }}"
  loop:
    - name: sops-3.7.1
      url: https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb
      filename: sops_3.7.1_amd64.deb
  tags:
    - sops
    - remote_archives
