- name: python | Create ~/pythons directory to store python-build Pythons
  become_user: "{{ username }}"
  ansible.builtin.file:
    state: directory
    path: "{{ home_dir }}/pythons"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - install
    - setup
    - python

- name: python | Install Python using upload archive method
  include_tasks: archive.yml
  when: python__install_method == "archive"

- name: python | Install Python using 'python-build'
  include_tasks: python-build.yml
  when: python__install_method == "python-build"

- name: python | Set Python [{{ python__default_version }}] as the 'default' Python with a symlink
  become_user: "{{ username }}"
  ansible.builtin.file:
    state: link
    src: "{{ home_dir }}/pythons/{{ python__default_version }}"
    dest: "{{ home_dir }}/pythons/default"
    owner: "{{ username }}"
    group: "{{ username }}"
  tags:
    - install
    - python

- name: python | Install 'virtualenvwrapper' into default ({{ python__default_version }}) Python in ~/pythons
  become_user: "{{ username }}"
  shell: |
    ./pip3 install virtualenvwrapper
  args:
    chdir: "{{ home_dir }}/pythons/default/bin"
    creates: "{{ home_dir }}/pythons/default/bin/virtualenvwrapper.sh"
  tags:
    - install
    - python
    - virtualenvwrapper
