---
# See: https://github.com/pyenv/pyenv/wiki/Common-build-problems
#
# Technically, these are the deps for all of `pyenv`, which `python-build`
# is a part of, but I didn't take the time to narrow down which ones are
# the only ones needed for using `python-build` (it would be very hard to do).
- name: Install dependencies for python-build
  become: yes
  apt:
    state: present
    name: "{{ python_python_build_deps }}"

# TODO: change to https URL
- name: Download python-build (part of pyenv)
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /tmp/pyenv
    version: v2.2.3

# NOTE: this also installs `pyenv-install` & `pyenv-uninstall` to /usr/local,
#       which we don't use
- name: Install python-build to /usr/local
  become: yes
  shell: PREFIX=/usr/local /bin/bash -c './install.sh -v'
  args:
    chdir: /tmp/pyenv/plugins/python-build
    creates: /usr/local/bin/python-build

- name: Create ~/pythons directory to store python-build Pythons
  become_user: "{{ username }}"
  file:
    state: directory
    path: "{{ home_dir }}/pythons"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install Python version 3.8.9 to ~/pythons with 'python-build'
  become_user: "{{ username }}"
  shell: ./python-build 3.8.9 "{{ home_dir }}/pythons/3.8.9"
  args:
    chdir: /usr/local/bin
    creates: "{{ home_dir }}/pythons/3.8.9/bin/python3"

- name: Set Python 3.8.9 as the 'default' Python with a symlink
  become_user: "{{ username }}"
  file:
    state: link
    src: "{{ home_dir }}/pythons/3.8.9"
    dest: "{{ home_dir }}/pythons/default"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install 'virtualenvwrapper' into default (3.8.9) Python in ~/pythons
  become_user: "{{ username }}"
  shell: ./pip3 install virtualenvwrapper
  args:
    chdir: "{{ home_dir }}/pythons/default/bin"
    creates: "{{ home_dir }}/pythons/default/bin/virtualenvwrapper.sh"
