---
- name: Configure hacker Vagrant VM
  hosts: hacker_vms
  become: yes
  vars:
    home_dir: /home/vagrant
    username: vagrant

  pre_tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 360
    # TODO: move to a role (required by golang role)
    - name: Setup downloads/srv directory
      file:
        state: directory
        name: "{{ downloads_srv_dir }}"

  roles:
    - role: hacker
      tags:
        - hacker

    - role: sudoers
      vars:
        sudoers_nopass_users: ["vagrant"]
      tags:
        - sudoers

    - role: go
      tags:
        - go

    - role: vim
      vars:
        vim_ycm_completers:
          - completer: go-completer
            creates: "{{ vim_bundle_dir }}/YouCompleteMe/third_party/ycmd/third_party/go/bin/gopls"
      tags:
        - vim

  tasks:
    - name: Setup bin directories
      file:
        state: directory
        path: "{{ home_dir }}/{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
      loop:
        - bin
        - .local/bin
      tags:
        - bashmarks

    - name: Install bashmarks
      get_url:
        url: https://raw.githubusercontent.com/huyng/bashmarks/master/bashmarks.sh
        dest: "{{ home_dir }}/.local/bin/bashmarks.sh"
        checksum: sha256:cee96f60a08e3801c851ddab43be188e450e39c097d4c4cb193a50ac847122c9
      tags:
        - bashmarks
