---
- name: Configure Lenovo Ubuntu 20.04 laptop (locally)
  hosts: lenovo
  connection: local
  become: yes

  tasks:

    - import_role:
        name: awscli
      tags:
        - awscli

    - import_role:
        name: common
      tags:
        - common

    - import_role:
        name: docker
      tags:
        - docker

    - import_role:
        name: hacker
      tags:
        - hacker

    - import_role:
        name: mmackey
      tags:
        - mmackey

    - import_role:
        name: sudoers
      tags:
        - sudoers


- name: Setup managed resolv.conf on DNS clients
  hosts: dns_clients
  become: yes
  tasks:
    - import_role:
        name: resolvconf
      tags:
        - resolvconf

