---
- name: Configure Lenovo Ubuntu 20.04 laptop (locally)
  hosts: lenovo
  connection: local
  become: yes
  roles:
    #- name: awscli
    #- name: common
    #- name: docker
    - name: epson_scanner
    #- name: hacker
    #- name: mmackey
    #- name: qemu-kvm
    #- name: sudoers
    #- name: virtual_machines
    #- name: vim

#- name: Setup managed resolv.conf on DNS clients
  #hosts: dns_clients
  #become: yes
  #tasks:
    #- import_role:
        #name: resolvconf
      #tags:
        #- resolvconf

