---
- name: Configure hacker vms
  hosts: hacker_vms

  pre_tasks:

    - name: Update APT cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 360

    # TODO: move to a role (required by golang role)
    - name: Setup downloads/srv directory
      file:
        state: directory
        name: "{{ downloads_srv_dir }}"

  roles:
    - role: go
    - role: hacker

