- name: Configure standard hacker VM (no-UI)
  hosts: hacker_vms
  roles:
    - role: base
    - role: dotfiles
    - role: devtools
    - role: crypt
    - role: docker
    - role: python
    - role: go
    - role: rust
    - role: openvpn
    - role: hacker

# This is to configure VM w/ Cinnamon GUI that we must access remotely (ie - on a Cloud VM)
- name: Setup HackTheBox VMs (Cloud VM)
  hosts: htb
  become: yes
  become_user: root
  roles:
    - role: cinnamon
    - role: xrdp
  tags:
    - never
    - htb

- name: Setup Kali Linux hacker VMs
  hosts: kali
  roles:
    # Prefer Alacritty terminal
    - role: alacritty
  tags:
    - kali
  # # Installing Gnome Terminal b/c couldn't get base16 to work on default Qt terminal w/ Kali
  # tasks:
  #   - name: Install Gnome Terminal
  #     apt:
  #       name: gnome-terminal
  #       state: present
