- name: Configure Kubernetes nodes
  hosts: k8s_cluster
  tasks:

    - name: Install common tools
      import_role:
        name: tools_common

    - name: Install common network tools
      import_role:
        name: tools_net

    - name: Setup Docker
      import_role:
        name: docker

    - name: Setup Kubernetes
      import_role:
        name: kubernetes
