---
- name: Configure HP Ubuntu 20.04 server
  hosts: mmhp
  vars:
    docker_docker_users:
      - mmachaj

  tasks:

    - import_role:
        name: tools_common
      tags:
        - common

    - import_role:
        name: tools_net
      tags:
        - common

    - import_role:
        name: docker
      tags:
        - docker

    - import_role:
        name: dnsmasq
      tags:
        - dns

    - import_role:
        name: hptower
      tags:
        - hptower

    - import_role:
        name: server
      tags:
        - server

    - import_role:
        name: sudoers
      tags:
        - sudoers

