---
- name: Configure Lenovo Ubuntu 20.04 laptop (locally)
  hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:

    - import_role:
        name: common
      tags:
        - common

    - import_role:
        name: docker
      tags:
        - docker

    - import_role:
        name: dnsmasq
      tags:
        - dns

    - import_role:
        name: mmackey
      tags:
        - mmackey

    - import_role:
        name: hacker
      tags:
        - hacker

    - import_role:
        name: awscli
      tags:
        - awscli
