---
- name: Configure HP Ubuntu 20.04 server
  hosts: mmhp
  become: yes
  vars:
    docker_docker_users:
      - mmachaj
  roles:
    #- hptower
    #- docker
    #- server
    #- dnsmasq
    #- qemu-kvm
    # - virtual_machines
      #    - xrdp

  #tasks:

    #- import_role:
        #name: docker
      #tags:
        #- docker

    #- import_role:
        #name: dnsmasq
      #tags:
        #- dns

    #- import_role:
        #name: hptower
      #tags:
        #- hptower

    #- import_role:
        #name: server
      #tags:
        #- server

    #- import_role:
        #name: sudoers
      #tags:
        #- sudoers
