---
- name: Disable systemd-resolved
  become: yes
  become_user: root
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

# NOTE: NM updates resolv.conf everytime the network connection changes, which
# is why this is needed to deploy resolv.conf changes that persist even after
# network connections changes OR reboots
- name: Disable NetworkManager DNS so it won't overwrite /etc/resolv.conf - dns setting
  become: yes
  become_user: root
  community.general.ini_file:
    state: present
    path: /etc/NetworkManager/NetworkManager.conf
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
  notify: resolvconf--restart-network-manager

# NOTE: for some reason, even though the docs say that all that is needed is to
# set dns=none in NetworkManager.conf, I have found that this setting also needs
# to be set sometimes
- name: Disable NetworkManager DNS so it won't overwrite /etc/resolv.conf - rc-manager setting
  become: yes
  become_user: root
  community.general.ini_file:
    state: present
    path: /etc/NetworkManager/NetworkManager.conf
    no_extra_spaces: yes
    section: main
    option: rc-manager
    value: unmanaged
    owner: root
    group: root
    mode: 0644
  notify: resolvconf--reload-network-manager

- name: Replace resolv.conf that was managed by system-resolved/NetworkManager
  become: yes
  become_user: root
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
    backup: yes

