---
- name: Configure hacker AWS VM
  hosts: aws
  become: yes
  # vars:
  #   home_dir: /home/ubuntu
  #   username: ubuntu

  pre_tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 360
    # TODO: move to a role (required by golang role)
    - name: Setup downloads/srv directory
      file:
        state: directory
        # not using base__ b/c we don't include base role
        name: "{{ home_downloads_dir }}"

  roles:
    - role: go
    - role: hacker
