---
- name: Configure development machines
  hosts: dev_machines
  roles:
    - base
    - resolvconf
    - 1password
    - crypt
    - devtools
    - net_tools
    - alacritty
    - ivpn
    - awscli
    - docker
    - docker_credentials_helper
    - go
    - google_cloud_sdk
    - hashicorp
    - moonlander
    - vscode
    - slack
    - wireshark
    - zoom
    - epson_scanner
    - printer
    - zaproxy
    - burpsuite
    - qemu_kvm

    # BROKEN
    # - flatpak

  # tasks:

    # - include_role:
    #     name: kubernetes
    #     tasks_from: repos.yml
    #     apply:
    #       tags:
    #          - kubectl
    #   tags:
    #     - always

    # - name: Install kubectl
    #   become: yes
    #   apt:
    #     name: kubectl
    #     state: present
    #   tags: kubectl
