- name: Run base playbook
  import_playbook: play-base.yml
  tags:
    - never

- name: Configure standard hacker VM (no-UI)
  hosts: hacker_vms
  roles:
    - role: dotfiles
    - role: devtools
    - role: crypt
    - role: docker
    - role: python
    - role: go
    - role: rust
    - role: openvpn
    - role: hacker
  tags:
    - never

# This is to configure VM w/ Cinnamon GUI that we must access remotely (ie - on a Cloud VM)
- name: Setup HackTheBox VMs (Cloud VM)
  hosts: htb
  become: yes
  become_user: root
  roles:
    - role: cinnamon
    - role: xrdp
  tags:
    - never
    - htb

- name: Setup standard hacker VM (GUI)
  hosts: hacker_vms_gui
  roles:
    - role: alacritty
    - role: wireshark
    - role: zaproxy

# - name: Setup Kali hacker VM (w/ GUI)
#   hosts: kali
  # # Installing Gnome Terminal b/c couldn't get base16 to work on default Qt terminal w/ Kali
  # tasks:
  #   - name: Install Gnome Terminal
  #     apt:
  #       name: gnome-terminal
  #       state: present
