---
- name: Install LastPass CLI debian dependencies
  apt:
    state: present
    name: "{{ item }}"
  loop:
    - bash-completion
    - build-essential
    - ca-certificates
    - cmake
    - libcurl4
    - libcurl4-openssl-dev
    - libssl1.1
    - libssl-dev
    - libxml2
    - libxml2-dev
    - pkg-config
    - xclip

# The `make` & `git` modules do NOT provided a `creates` option so using this
# test instead:
- name: Check if LastPass CLI is already installed
  stat:
    path: /usr/bin/lpass
  register: lastpass_cli

- name: Download lastpass-cli from Github
  git:
    repo: https://github.com/lastpass/lastpass-cli.git
    dest: /tmp/lastpass-cli
    version: v1.3.3
  when: lastpass_cli.stat.exists == False

- name: Build lastpass-cli source
  make:
    chdir: /tmp/lastpass-cli
  when: lastpass_cli.stat.exists == False

- name: Install lastpass-cli from built source
  become: yes
  make:
    chdir: /tmp/lastpass-cli
    target: install
  when: lastpass_cli.stat.exists == False

- name: Install LastPass CLI documentation debian dependencies
  become: yes
  apt:
    state: latest
    name: "{{ item }}"
  loop:
    - asciidoc
    - xsltproc

# The `make` module does NOT provided a `creates` option so using this
# test instead:
- name: Check if LastPass CLI docs are already installed
  stat:
    path: /usr/share/man/man1/lpass.1
  register: lastpass_cli_docs

- name: Install lastpass-cli man page
  become: yes
  make:
    chdir: /tmp/lastpass-cli
    target: install-doc
  when: lastpass_cli_docs.stat.exists == False
