---
python_python_build_deps:
  - build-essential
  - curl
  - git
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - llvm
  - python-openssl
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev
