python__default_version: 3.8.9
python__install_method: archive
python__pyenv_version: v2.2.3
python__python_build_deps:
  - build-essential
  - curl
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - libxml2-dev
  - libxmlsec1-dev
  - llvm
  - tk-dev
  - xz-utils
  - zlib1g-dev
