---
- name: Install packages that allow APT to be used over HTTPS
  become: yes
  apt:
    name: "{{ apt_https_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  vars:
    apt_https_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
