---
username: mmachaj
home_dir: /home/{{ username }}
sudoers_nopass_users:
  - app
  - cm
  - mmachaj
  - mmackey
users:
  - name: app
    gecos: App
    groups:
      - docker
  - name: cm
    gecos: Config Management
    groups: []
