---
- name: Set postfix main mailer type debconf selection
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: "Internet Site"
    vtype: select

- name: Set postfix mailname debconf selection
  debconf:
    name: postfix
    question: postfix/mailname
    value: localhost
    vtype: string

- name: Set postfix destinations debconf selection
  debconf:
    name: postfix
    question: postfix/destinations
    #value: "localhost.localdomain, localhost"
    value: "localhost.$mydomain, localhost, $myhostname"
    vtype: string

- name: Install postfix package & related utilities
  apt:
    name: mailutils
    state: present
    update_cache: yes
    cache_valid_time: 3600

