- name: resolvconf--reload-network-manager
  become: yes
  become_user: root
  service:
    name: NetworkManager
    state: reloaded

- name: resolvconf--restart-network-manager
  become: yes
  become_user: root
  service:
    name: NetworkManager
    state: restarted
