devtools__packages:
  # For Neo4J
  - cypher-shell
  - httpie
  - mysql-client
  - postgresql-client
  # Provides: redis-cli
  - redis-tools
  - sqlite3

devtools__packages_full:
  # Used for making cloud-init seed ISOs
  - cloud-utils
  - graphviz
  - universal-ctags

devtools__snaps:
  - postman

devtools__remote_debs: []

devtools__remote_archives: []
