---
install_type: minimal

is_gui: no
is_server: no

username: "{{ ansible_user_id }}"
home_dir: /home/{{ username }}

base__user: "{{ username }}"

base__ansible_srv_dir: /srv/ansible
base__bin_dir: /srv/ansible/bin
base__downloads_dir: /srv/ansible/downloads
base__git_dir: /srv/ansible/git

sudoers__nopass_users:
  - "{{ username }}"

# TODO: replace one of these two variables since they are dups
home_downloads_dir: "{{ home_dir }}/downloads/srv"
home_downloads_srv_dir: "{{ home_dir }}/downloads/srv"

ansible_bash_dir: "/home/{{ username }}/.local/ansible_bash"

nfs_mount_dir: /mnt/mmackey-sync
nfs_mount_str: 192.168.1.253:/{{ nfs_mount_dir }}
nfs__exports_str: "{{ nfs_mount_dir }} 192.168.1.0/24(rw,sync,no_subtree_check)"


# -------------------------------------------------------------------------------
# UNUSED - need to create roles to install these (or just keep for ref)
# -------------------------------------------------------------------------------
ide__packages:
  - atom
  - roxterm
  - sublime-text-installer

r_lang__packages:
  - r-base-dev
  # For 'devtools' R package
  - libcurl4-openssl-dev
  # For 'devtools' R package
  - libxml2-dev
