#-------------------------------------------------------------------------------
# HOW TO USE:
#
# - name: Install remote .debs
#   include_tasks:
#     file: global__install_remote_deb.yml
#   # Example loop variable:
#   loop:
#      - name: microsoft-teams
#        url: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.10453_amd64.deb
#        filename: teams_1.5.00.10453_amd64.deb
#        checksum: sha256:7cb570d9ac5231eb6e6a84738e0fb1e0345863c58fe5341b2fb2db7c5e8b15f0
#
#-------------------------------------------------------------------------------
- block:
  - name: global (remote_deb) | Download .deb file w/ checksum ({{ item.name }})
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ base__downloads_dir }}/{{ item.filename }}"
      checksum: "{{ item.checksum }}"
    when: item.checksum is defined and item.checksum != ""

  - name: global (remote_deb) | Download .deb file w/o checksum ({{ item.name }})
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ base__downloads_dir }}/{{ item.filename }}"
    when: item.checksum is not defined or item.checksum == ""

  # TODO: validate .deb checksum
  - name: TODO | global (remote_deb) | Verify checksum of .deb ({{ item.name }})
    debug:
      msg: "IMPLEMENT ME"
    when: False

  - name: global (remote_deb) | Install package via .deb ({{ item.name }})
    become: yes
    become_user: root
    ansible.builtin.apt:
      state: present
      deb: "{{ base__downloads_dir }}/{{ item.filename }}"
  tags:
    - remote_debs
