---
- name: kubelet_daemon_reload_restart
  become: yes
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: kubelet_restart
  become: yes
  systemd:
    name: kubelet
    state: restarted
