#------------------------------------------------------------------------------
# Install: Go
#------------------------------------------------------------------------------
#-------------------------------------------------------------------
# Go tools (TEMPLATE for later??)
##-------------------------------------------------------------------
#- name: hacker | install Go tool ({{ item.name }})
#  shell: |
#    go install -v {{ item.url }}@{{ item.version }}
#  args:
#    creates: "/home/{{ ansible_user_id }}/go/bin/{{ item.exec }}"
#    # Needed to activate GOPATH
#    executable: /bin/bash
#  tags:
#    - install
#    - hacker
#    - hacker__bug_bounty
#    - hacker__go_tools
#  loop: "{{ hacker__go_tools }}"

#-------------------------------------------------------------------
# amass
#-------------------------------------------------------------------
- name: hacker | amass | install amass
  shell: |
    go install -v github.com/OWASP/Amass/v3/...@{{ hacker__amass_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/amass"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__amass
  when: hacker__install_amass | bool

#-------------------------------------------------------------------
# anew
#-------------------------------------------------------------------
- name: hacker | anew | install anew
  shell: |
    go get -u github.com/tomnomnom/anew
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/anew"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__anew
    - hacker__tomnomnom
  when: hacker__install_anew | bool

#-------------------------------------------------------------------
# assetfinder
#-------------------------------------------------------------------
- name: hacker | assetfinder | install assetfinder
  shell: |
    go get -u github.com/tomnomnom/assetfinder
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/assetfinder"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__assetfinder
    - hacker__tomnomnom
  when: hacker__install_assetfinder | bool

#-------------------------------------------------------------------
# blocksort
#-------------------------------------------------------------------
- name: hacker | blocksort | install blocksort
  shell: |
    go get -u github.com/tomnomnom/blocksort
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/blocksort"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__blocksort
    - hacker__tomnomnom
  when: hacker__install_blocksort | bool

#-------------------------------------------------------------------
# fff
#-------------------------------------------------------------------
- name: hacker | fff | install fff
  shell: |
    go get -u github.com/tomnomnom/fff
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/fff"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__fff
    - hacker__tomnomnom
  when: hacker__install_fff | bool

#-------------------------------------------------------------------
# ffuf
#-------------------------------------------------------------------
- name: hacker | ffuf | install ffuf
  shell: |
    go install -v github.com/ffuf/ffuf/v2@{{ hacker__ffuf_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/ffuf"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__ffuf
  when: hacker__install_ffuf | bool

#-------------------------------------------------------------------
# gau
#-------------------------------------------------------------------
- name: hacker | gau | install gau
  shell: |
    go install -v github.com/lc/gau/v2/cmd/gau@{{ hacker__gua_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/gau"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gau
  when: hacker__install_gau | bool

#-------------------------------------------------------------------
# gf
#-------------------------------------------------------------------
- name: hacker | gf | install gf
  shell: |
    go get -u github.com/tomnomnom/gf
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/gf"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gf
    - hacker__tomnomnom
  when: hacker__install_gf | bool

#-------------------------------------------------------------------
# goaltdns
#-------------------------------------------------------------------
- name: hacker | goaltdns | install goaltdns
  shell: |
    go get -u github.com/subfinder/goaltdns
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/goaltdns"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__goaltdns
  when: hacker__install_goaltdns | bool

#-------------------------------------------------------------------
# gobuster
#-------------------------------------------------------------------
- name: hacker | gobuster | install gobuster
  shell: |
    go install -v github.com/OJ/gobuster/v3@{{ hacker__gobuster_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/gobuster"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gobuster
  when: hacker__install_gobuster | bool

#-------------------------------------------------------------------
# gron
#-------------------------------------------------------------------
- name: hacker | gron | install gron
  shell: |
    go get -u github.com/tomnomnom/gron
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/gron"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gron
    - hacker__tomnomnom
  when: hacker__install_gron | bool

#-------------------------------------------------------------------
# hakrawler
#-------------------------------------------------------------------
- name: hacker | hakrawler | install hakrawler
  shell: |
    go install -v github.com/hakluke/hakrawler@{{ hacker__hakrawler_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/hakrawler"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__hakrawler
  when: hacker__install_hakrawler | bool

#-------------------------------------------------------------------
# gospider
#-------------------------------------------------------------------
- name: hacker | gospider | install gospider
  shell: |
    go install -v github.com/jaeles-project/gospider@{{ hacker__gospider_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/gospider"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gospider
  when: hacker__install_gospider | bool

#-------------------------------------------------------------------
# fingerprintx
#-------------------------------------------------------------------
- name: hacker | fingerprintx | install fingerprintx
  shell: |
    go install -v github.com/praetorian-inc/fingerprintx/cmd/fingerprintx@{{ hacker__fingerprintx_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/fingerprintx"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__fingerprintx
  when: hacker__install_fingerprintx | bool

#-------------------------------------------------------------------
# gowitness
#-------------------------------------------------------------------
- name: hacker | gowitness | install gowitness
  shell: |
    go install -v github.com/sensepost/gowitness@{{ hacker__gowitness_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/gowitness"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gowitness
  when: hacker__install_gowitness | bool


#-------------------------------------------------------------------
# httprobe
#-------------------------------------------------------------------
- name: hacker | httprobe | install httprobe
  shell: |
    go install -v github.com/tomnomnom/httprobe@{{ hacker__httprobe_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/httprobe"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__httprobe
    - hacker__tomnomnom
  when: hacker__install_httprobe | bool

#-------------------------------------------------------------------
# httpx
#-------------------------------------------------------------------
- name: hacker | httpx | install httpx
  shell: |
    go install -v github.com/projectdiscovery/httpx/cmd/httpx@{{ hacker__httpx_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/httpx"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__httpx
  when: hacker__install_httpx | bool

#-------------------------------------------------------------------
# meg
#-------------------------------------------------------------------
- name: hacker | meg | install meg
  shell: |
    go get -u github.com/tomnomnom/meg
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/meg"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__meg
    - hacker__tomnomnom
  when: hacker__install_meg | bool

#-------------------------------------------------------------------
# nuclei
#-------------------------------------------------------------------
- name: hacker | nuclei | install nuclei
  shell: |
    go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@{{ hacker__nuclei_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/nuclei"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__nuclei
  when: hacker__install_nuclei | bool

#-------------------------------------------------------------------
# qsreplace
#-------------------------------------------------------------------
- name: hacker | qsreplace | install qsreplace
  shell: |
    go get -u github.com/tomnomnom/qsreplace
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/qsreplace"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__qsreplace
    - hacker__tomnomnom
  when: hacker__install_qsreplace | bool

#-------------------------------------------------------------------
# subfinder
#-------------------------------------------------------------------
- name: hacker | subfinder | install subfinder
  shell: |
    go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@{{ hacker__subfinder_version }}
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/subfinder"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__subfinder
  when: hacker__install_subfinder | bool

#-------------------------------------------------------------------
# unfurl
#-------------------------------------------------------------------
- name: hacker | unfurl | install unfurl
  shell: |
    go get -u github.com/tomnomnom/unfurl
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/unfurl"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__unfurl
    - hacker__tomnomnom
  when: hacker__install_unfurl | bool

#-------------------------------------------------------------------
# waybackurls
#-------------------------------------------------------------------
- name: hacker | waybackurls | install waybackurls
  shell: |
    go get -u github.com/tomnomnom/waybackurls
  args:
    creates: "/home/{{ ansible_user_id }}/go/bin/waybackurls"
    # Needed to activate GOPATH
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__waybackurls
    - hacker__tomnomnom
  when: hacker__install_waybackurls | bool


#------------------------------------------------------------------------------
# Install: Python
#
# These are Python tools I want to install but are hard to with Ansible b/c they
# involve virtualenvs:
#
#  - https://github.com/aboul3la/Sublist3r
#  - https://github.com/ProjectAnte/dnsgen
#------------------------------------------------------------------------------

#-------------------------------------------------------------------
# altdns
#-------------------------------------------------------------------
- name: hacker | altdns | install altdns into hacker virtualenv via PyPi (not source)
  shell: |
    source {{ hacker__virtualenv_activate }}
    pip3 install py-altdns=={{ hacker__altdns_version }}
    deactivate
  args:
    creates: "{{ hacker__virtualenv_dir }}/bin/altdns"
    executable: /bin/bash
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__altdns
  when: hacker__install_altdns | bool


#------------------------------------------------------------------------------
# Install: Git
#------------------------------------------------------------------------------

#-------------------------------------------------------------------
# altdns-wordlist
#-------------------------------------------------------------------
- name: hacker | altdns | clone altdns repository
  ansible.builtin.git:
    repo: https://github.com/infosec-au/altdns.git
    dest: "{{ hacker__tools_dir }}/altdns"
    version: "{{ hacker__altdns_wordlist_version }}"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__altdns_wordlist
  when: hacker__install_altdns_wordlist | bool

#-------------------------------------------------------------------
# ExploitDB/Searchsploit
#-------------------------------------------------------------------
- name: hacker | exploitdb/searchsploit | install exploitdb/searchsploit
  block:
    - name: hacker | exploitdb/searchsploit | download exploitdb project w/ searchsploit tools
      ansible.builtin.git:
        repo: 'https://github.com/offensive-security/exploitdb.git'
        version: "{{ hacker__exploitdb_searchsploit_version }}"
        dest: "{{ hacker__tools_dir }}/exploitdb"

    - name: hacker | exploitdb/searchsploit | symlink searchsploit into PATH from exploitdb project
      ansible.builtin.file:
        state: link
        src: "{{ hacker__tools_dir }}/exploitdb/searchsploit"
        dest: "{{ hacker__tools_bin_dir }}/searchsploit"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__exploitdb
    - hacker__searchsploit
    - hacker__large
  when: hacker__install_exploitdb_searchsploit | bool

#-------------------------------------------------------------------
# massdns
#-------------------------------------------------------------------
- name: hacker | massdns | install massdns
  block:
    - name: hacker | massdns | clone massdns repository
      ansible.builtin.git:
        repo: https://github.com/blechschmidt/massdns
        dest: "{{ hacker__massdns_home }}"
        version: "{{ hacker__massdns_version }}"

    - name: hacker | massdns | build massdns from source
      command: make
      args:
        chdir: "{{ hacker__massdns_home }}"
        creates: "{{ hacker__massdns_home }}/bin/massdns"

    - name: hacker | massdns | symlink massdns binary into the PATH
      ansible.builtin.file:
        state: link
        src: "{{ hacker__massdns_home }}/bin/massdns"
        dest: "{{ hacker__tools_bin_dir }}/massdns"
  vars:
    hacker__massdns_home: "{{ hacker__tools_dir }}/massdns"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__massdns
  when: hacker__install_massdns | bool

#-------------------------------------------------------------------
# sqlmap
#-------------------------------------------------------------------
- name: hacker | sqlmap | install sqlmap
  block:
    - name: hacker | sqlmap | clone sqlmap repository
      ansible.builtin.git:
        repo: https://github.com/sqlmapproject/sqlmap.git
        dest: "{{ hacker__sqlmap_home }}"
        version: "{{ hacker__sqlmap_version }}"

    - name: hacker | sqlmap | symlink sqlmap binary into the PATH
      ansible.builtin.file:
        state: link
        src: "{{ hacker__sqlmap_home }}/sqlmap.py"
        dest: "{{ hacker__tools_bin_dir }}/sqlmap"
  vars:
    hacker__sqlmap_home: "{{ hacker__tools_dir }}/sqlmap"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__sqlmap
  when: hacker__install_sqlmap | bool

#-------------------------------------------------------------------
# SecLists
#-------------------------------------------------------------------
- name: hacker | SecLists | install SecLists
  ansible.builtin.git:
    repo: https://github.com/danielmiessler/SecLists.git
    version: "{{ hacker__seclists_version }}"
    dest: "{{ hacker__tools_dir }}/SecLists"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__seclists
    - hacker__large
  when: hacker__install_seclists | bool


#------------------------------------------------------------------------------
# Install: Shell
#------------------------------------------------------------------------------

#-------------------------------------------------------------------
# Metasploit
#
# The `msfinstall` program will install APT keys and the `metasploit-framework` package
# (or does it?? - this doesn't run as root so I don't know how it can).
#
# See: https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html
#-------------------------------------------------------------------
- name: hacker | metasploit | install metasploit via their omnibus installer
  shell: |
    curl {{ hacker__metasploit_installer_url }} > /tmp/msfinstall && \
    chmod 755 /tmp/msfinstall && \
    /tmp/msfinstall
  args:
    creates: /opt/metasploit-framework/bin/msfconsole
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__metasploit
    - hacker__large
  when: hacker__install_metasploit | bool
