#-------------------------------------------------------------------
# amass
#-------------------------------------------------------------------
- name: hacker | install amass
  shell: |
    go install -v github.com/OWASP/Amass/v3/...@master
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/amass"
  tags:
    - hacker
    - hacker__amass

#-------------------------------------------------------------------
# ExploitDB: Searchsploit
#-------------------------------------------------------------------
- name: hacker - install exploitdb/searchsploit
  tags:
    - hacker
    - hacker__searchsploit
  when: hacker__install_searchsploit | bool
  block:
    - name: hacker | download exploitdb project w/ searchsploit tools
      ansible.builtin.git:
        repo: 'https://github.com/offensive-security/exploitdb.git'
        version: "{{ hacker__exploitdb_version }}"
        dest: "{{ hacker__tools_dir }}/exploitdb"

    - name: hacker | symlink searchsploit into PATH from exploitdb project
      ansible.builtin.file:
        state: link
        src: "{{ hacker__tools_dir }}/exploitdb/searchsploit"
        dest: "{{ hacker__tools_bin_dir }}/searchsploit"

#-------------------------------------------------------------------
# ffuf
#-------------------------------------------------------------------
- name: hacker | install ffuf
  shell: |
    go install github.com/ffuf/ffuf@latest
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/ffuf"
  tags:
    - hacker
    - hacker__ffuf

#-------------------------------------------------------------------
# gobuster
#-------------------------------------------------------------------
- name: hacker | install gobuster
  shell: |
    go install github.com/OJ/gobuster/v3@latest
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/gobuster"
  tags:
    - hacker
    - hacker__gobuster

#-------------------------------------------------------------------
# httprobe
#-------------------------------------------------------------------
- name: hacker | install httprobe
  shell: |
    go install github.com/tomnomnom/httprobe@latest
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/httprobe"
  tags:
    - hacker
    - hacker__httprobe

#-------------------------------------------------------------------
# massdns
#-------------------------------------------------------------------
- name: hacker | Block for massdns
  tags:
    - hacker
    - hacker__massdns
  vars:
    hacker__massdns_home: "{{ hacker__tools_dir }}/massdns"
  block:
    - name: hacker | clone massdns repository
      ansible.builtin.git:
        repo: https://github.com/blechschmidt/massdns
        dest: "{{ hacker__massdns_home }}"
        version: "{{ hacker__massdns_version }}"

    - name: hacker | build massdns from source
      command: make
      args:
        chdir: "{{ hacker__massdns_home }}"
        creates: "{{ hacker__massdns_home }}/bin/massdns"

    - name: hacker | symlink massdns binary into the PATH
      ansible.builtin.file:
        state: link
        src: "{{ hacker__massdns_home }}/bin/massdns"
        dest: "{{ hacker__tools_bin_dir }}/massdns"

#-------------------------------------------------------------------
# Metasploit
#
# The `msfinstall` program will install APT keys and the `metasploit-framework` package.
#
# See: https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html
#-------------------------------------------------------------------
- name: hacker | install metasploit via their omnibus installer
  shell: |
    curl \
      https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > /tmp/msfinstall && \
    chmod 755 /tmp/msfinstall && \
    /tmp/msfinstall
  args:
    creates: /opt/metasploit-framework/bin/msfconsole
  tags:
    - hacker
    - hacker__metasploit
  when: hacker__install_metasploit | bool

#-------------------------------------------------------------------
# subfinder
#-------------------------------------------------------------------
- name: hacker | install subfinder
  shell: |
    go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/subfinder"
  tags:
    - hacker
    - hacker__subfinder

#-------------------------------------------------------------------
# Wordlists / Data
#-------------------------------------------------------------------
- name: hacker | install packages - wordlists
  ansible.builtin.git:
    repo: https://github.com/danielmiessler/SecLists.git
    version: '2021.2'
    dest: "{{ hacker__tools_dir }}/SecLists"
  tags:
    - hacker
    - hacker__wordlists
  when: hacker__install_wordlists | bool

