#------------------------------------------------------------------------------
# These are Python tools I want to install but are hard to with Ansible b/c they
# involve virtualenvs:
#
#  - https://github.com/aboul3la/Sublist3r
#  - https://github.com/ProjectAnte/dnsgen
#------------------------------------------------------------------------------

#-------------------------------------------------------------------
# altdns
#-------------------------------------------------------------------
- name: hacker | install altdns into hacker virtualenv via PyPi (not source)
  shell: |
    source {{ hacker__virtualenv_activate }}
    pip3 install py-altdns=={{ hacker__altdns_version }}
    deactivate
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__altdns
  when: hacker__install_altdns | bool

#-------------------------------------------------------------------
# altdns-wordlist
#-------------------------------------------------------------------
- name: hacker | clone altdns repository
  ansible.builtin.git:
    repo: https://github.com/infosec-au/altdns.git
    dest: "{{ hacker__tools_dir }}/altdns"
    version: "{{ hacker__altdns_wordlist_version }}"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__altdns_wordlist
  when: hacker__install_altdns_wordlist | bool

#-------------------------------------------------------------------
# amass
#-------------------------------------------------------------------
- name: hacker | install amass
  shell: |
    go install -v github.com/OWASP/Amass/v3/...@{{ hacker__amass_version }}
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/amass"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__amass
  when: hacker__install_amass | bool

#-------------------------------------------------------------------
# assetfinder
#-------------------------------------------------------------------
- name: hacker | install assetfinder
  shell: |
    go get -u github.com/tomnomnom/assetfinder
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/assetfinder"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__assetfinder
  when: hacker__install_assetfinder | bool

#-------------------------------------------------------------------
# ExploitDB/Searchsploit
#-------------------------------------------------------------------
- name: hacker - install exploitdb/searchsploit
  block:
    - name: hacker | download exploitdb project w/ searchsploit tools
      ansible.builtin.git:
        repo: 'https://github.com/offensive-security/exploitdb.git'
        version: "{{ hacker__exploitdb_searchsploit_version }}"
        dest: "{{ hacker__tools_dir }}/exploitdb"

    - name: hacker | symlink searchsploit into PATH from exploitdb project
      ansible.builtin.file:
        state: link
        src: "{{ hacker__tools_dir }}/exploitdb/searchsploit"
        dest: "{{ hacker__tools_bin_dir }}/searchsploit"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__exploitdb
    - hacker__searchsploit
  when: hacker__install_exploitdb_searchsploit | bool

#-------------------------------------------------------------------
# ffuf
#-------------------------------------------------------------------
- name: hacker | install ffuf
  shell: |
    go install github.com/ffuf/ffuf@{{ hacker__ffuf_version }}
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/ffuf"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__ffuf
  when: hacker__install_ffuf | bool

#-------------------------------------------------------------------
# goaltdns
#-------------------------------------------------------------------
- name: hacker | install goaltdns
  shell: |
    go get -u github.com/subfinder/goaltdns
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/goaltdns"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__goaltdns
  when: hacker__install_goaltdns | bool

#-------------------------------------------------------------------
# gobuster
#-------------------------------------------------------------------
- name: hacker | install gobuster
  shell: |
    go install github.com/OJ/gobuster/v3@{{ hacker__gobuster_version }}
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/gobuster"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__gobuster
  when: hacker__install_gobuster | bool

#-------------------------------------------------------------------
# httprobe
#-------------------------------------------------------------------
- name: hacker | install httprobe
  shell: |
    go install github.com/tomnomnom/httprobe@{{ hacker__httprobe_version }}
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/httprobe"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__httprobe
  when: hacker__install_httprobe | bool

#-------------------------------------------------------------------
# massdns
#-------------------------------------------------------------------
- name: hacker | install massdns
  block:
    - name: hacker | clone massdns repository
      ansible.builtin.git:
        repo: https://github.com/blechschmidt/massdns
        dest: "{{ hacker__massdns_home }}"
        version: "{{ hacker__massdns_version }}"

    - name: hacker | build massdns from source
      command: make
      args:
        chdir: "{{ hacker__massdns_home }}"
        creates: "{{ hacker__massdns_home }}/bin/massdns"

    - name: hacker | symlink massdns binary into the PATH
      ansible.builtin.file:
        state: link
        src: "{{ hacker__massdns_home }}/bin/massdns"
        dest: "{{ hacker__tools_bin_dir }}/massdns"
  vars:
    hacker__massdns_home: "{{ hacker__tools_dir }}/massdns"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__massdns
  when: hacker__install_massdns | bool

#-------------------------------------------------------------------
# Metasploit
#
# The `msfinstall` program will install APT keys and the `metasploit-framework` package.
#
# See: https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html
#-------------------------------------------------------------------
- name: hacker | install metasploit via their omnibus installer
  shell: |
    curl {{ hacker__metasploit_installer_url }} > /tmp/msfinstall && \
    chmod 755 /tmp/msfinstall && \
    /tmp/msfinstall
  args:
    creates: /opt/metasploit-framework/bin/msfconsole
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__metasploit
  when: hacker__install_metasploit | bool

#-------------------------------------------------------------------
# nuclei
#-------------------------------------------------------------------
- name: hacker | install nuclei
  shell: |
    go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@{{ hacker__nuclei_version }}
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/nuclei"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__nuclei
  when: hacker__install_nuclei | bool

#-------------------------------------------------------------------
# SecLists
#-------------------------------------------------------------------
- name: hacker | install SecLists
  ansible.builtin.git:
    repo: https://github.com/danielmiessler/SecLists.git
    version: "{{ hacker__seclists_version }}"
    dest: "{{ hacker__tools_dir }}/SecLists"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__seclists
  when: hacker__install_seclists | bool

#-------------------------------------------------------------------
# subfinder
#-------------------------------------------------------------------
- name: hacker | install subfinder
  shell: |
    go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@{{ hacker__subfinder_version }}
  args:
    creates: "/home/{{ ansible_ssh_user }}/go/bin/subfinder"
  tags:
    - install
    - hacker
    - hacker__bug_bounty
    - hacker__subfinder
  when: hacker__install_subfinder | bool
