---
# Checksum is hard-coded here b/c they don't have checksum files to download,
# just checksums to view on the download webpage
- name: hacker | burp | Download Burp Suite Community installer
  ansible.builtin.get_url:
    url: "{{ hacker__burp_installer_url }}"
    dest: "{{ downloads_dir }}/{{ hacker__burp_installer_filename }}"
    checksum: "{{ hacker__burp_installer_checksum }}"
    mode: '0755'

# TODO: Consider using '-overwrite' option with un-attended install
- name: hacker | burp | Run un-attended Burp Suite Community installer
  become: yes
  shell: |
    {{ downloads_dir }}/{{ hacker__burp_installer_filename }} -q
  args:
    creates: /opt/BurpSuiteCommunity/BurpSuiteCommunity
