#-------------------------------------------------------------------
# Hardware tools
#-------------------------------------------------------------------
- name: hacker | install packages - hardware tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_hardware }}"
  vars:
    hacker__packages_hardware:
      - bluez-hcidump
  tags:
    - hacker
    - hacker__hardware
