#-------------------------------------------------------------------
# John the Ripper
#-------------------------------------------------------------------
- name: hacker | install John the Ripper from source
  vars:
    hacker__john_home: "{{ hacker__tools_dir }}/john"
    hacker__packages_john_dependencies:
      - build-essential
      - git
      - libbz2-dev
      - libgmp-dev
      - libpcap-dev
      - libssl-dev
      - pkg-config
      - yasm
      - zlib1g-dev
  block:
    - name: hacker | install John the Ripper dependencies
      become: yes
      become_user: root
      ansible.builtin.apt:
        state: present
        name: "{{ hacker__packages_john_dependencies }}"
      tags:
        - setup
        - hacker
        - hacker__john

    - name: hacker | checkout latest John the Ripper source code
      ansible.builtin.git:
        repo: https://github.com/openwall/john
        dest: "{{ hacker__john_home }}"
        version: "{{ hacker__john_version }}"
      tags:
        - install
        - hacker
        - hacker__john

    - name: hacker | build John the Ripper from source
      shell: |
        ./configure && make -s clean && make -sj4
      args:
        chdir: "{{ hacker__john_home }}/src"
        creates: "{{ hacker__john_home }}/run/john"
      tags:
        - install
        - hacker
        - hacker__john

    - name: hacker | symlink John the Ripper binary into the PATH
      ansible.builtin.file:
        state: link
        src: "{{ hacker__john_home }}/run/john"
        dest: "{{ hacker__tools_bin_dir }}/john"
      tags:
        - install
        - hacker
        - hacker__john
