#-------------------------------------------------------------------
# Setup tools directories
#-------------------------------------------------------------------
- name: hacker | setup hacker directories
  become: yes
  become_user: root
  tags:
    - setup
    - hacker
    - hacker__setup
  block:
    - name: hacker | create "hacker" group
      ansible.builtin.group:
        name: hacker
        state: present

    - name: hacker | add developer user ({{ common__user }}) to "hacker" group
      ansible.builtin.user:
        name: "{{ common__user }}"
        groups: hacker
        append: yes

    - name: hacker | create hacker tools directory
      ansible.builtin.file:
        state: directory
        dest: "{{ hacker__tools_dir }}"
        owner:  root
        group:  hacker
        mode: 0775

    - name: hacker | create tools bin directory
      ansible.builtin.file:
        state: directory
        dest: "{{ hacker__tools_bin_dir }}"
        owner: root
        group: hacker
        mode: 0775

#-------------------------------------------------------------------
# Common
#-------------------------------------------------------------------
- name: hacker | install packages - common tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_common }}"
  vars:
    hacker__packages_common:
      - ascii
  tags:
    - install
    - hacker
    - hacker__common
    #
#-------------------------------------------------------------------
# CTF Tools
#-------------------------------------------------------------------
- name: hacker | install packages - CTF tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_ctf }}"
  vars:
    hacker__packages_ctf:
      - hashcash
  tags:
    - install
    - hacker
    - hacker__ctf

#-------------------------------------------------------------------
# Hardware tools
#-------------------------------------------------------------------
- name: hacker | install packages - hardware tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_hardware }}"
  vars:
    hacker__packages_hardware:
      - bluez-hcidump
  tags:
    - install
    - hacker
    - hacker__hardware

#-------------------------------------------------------------------
# Forensics
#-------------------------------------------------------------------
- name: hacker | install packages - forensics tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_forensics }}"
  vars:
    hacker__packages_forensics:
      - binwalk
      - foremost
      - steghide
  tags:
    - install
    - hacker
    - hacker__forensics

#-------------------------------------------------------------------
# Reverse Engineering
#-------------------------------------------------------------------
- name: hacker | install packages - reverse engineering tools
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_reverse_engr }}"
  vars:
    hacker__packages_reverse_engr:
      - fs-uae
      - fs-uae-launcher
  tags:
    - install
    - hacker
    - hacker__reverse_engr

#-------------------------------------------------------------------
# John the Ripper
#-------------------------------------------------------------------
- import_tasks: john_the_ripper.yml

#-------------------------------------------------------------------
# Bug Bounty
#-------------------------------------------------------------------
- import_tasks: bug_bounty.yml
