#-------------------------------------------------------------------
# Setup tools directories
#-------------------------------------------------------------------
- name: hacker | setup hacker directories
  become: yes
  become_user: root
  tags:
    - hacker
    - hacker__setup
  block:
    - name: hacker | create "hacker" group
      ansible.builtin.group:
        name: hacker
        state: present

    - name: hacker | add developer user ({{ common__user }}) to "hacker" group
      ansible.builtin.user:
        name: "{{ common__user }}"
        groups: hacker
        append: yes

    - name: hacker | create hacker tools directory
      ansible.builtin.file:
        state: directory
        dest: "{{ hacker__tools_dir }}"
        owner:  root
        group:  hacker
        mode: 0775

    - name: hacker | create tools bin directory
      ansible.builtin.file:
        state: directory
        dest: "{{ hacker__tools_bin_dir }}"
        owner: root
        group: hacker
        mode: 0775

#-------------------------------------------------------------------
# Common
#-------------------------------------------------------------------
- name: hacker | install packages - common
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_common }}"
  vars:
    hacker__packages_common:
      - ack-grep
      - ascii
      - bzip2
      - curl
      - fd-find
      - fzf
      - git
      - gzip
      - htop
      - jq
      - pigz
      - p7zip-full
      - ripgrep
      - tmux
      - tree
      - wget
      - xclip
      - xsel
      - xz-utils
  tags:
    - hacker
    - hacker__common

#-------------------------------------------------------------------
# DB
#-------------------------------------------------------------------
- name: hacker | install packages - DB
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ hacker__packages_db }}"
  vars:
    hacker__packages_db:
      - mysql-client
      - sqlite3
  tags:
    - hacker
    - hacker__db

#-------------------------------------------------------------------
# Network
#-------------------------------------------------------------------
- name: hacker - network tools
  become: yes
  become_user: root
  vars:
    hacker__packages_net_tools:
      - arping
      - arp-scan
      - iputils-ping
      - iputils-tracepath
      - net-tools
      - nikto
      - nmap
      - tshark
      - whois
    hacker__packages_net_tools_gui:
      - wireshark
  block:
    - name: hacker | install packages - network tools
      ansible.builtin.apt:
        state: present
        name: "{{ hacker__packages_net_tools }}"
      tags:
        - hacker
        - hacker__net_tools

    - name: hacker | install packages - network tools (GUI)
      ansible.builtin.apt:
        state: present
        name: "{{ hacker__packages_net_tools_gui }}"
      vars:
      tags:
        - hacker
        - hacker__net_tools_gui
        - gui

#-------------------------------------------------------------------
# Bug Bounty
#-------------------------------------------------------------------
- import_tasks: bug_bounty.yml

#-------------------------------------------------------------------
# CTF
#-------------------------------------------------------------------
- import_tasks: ctf.yml

#-------------------------------------------------------------------
# Hardware
#-------------------------------------------------------------------
- import_tasks: hardware.yml

#-------------------------------------------------------------------
# Reverse Engineering / Forensics
#-------------------------------------------------------------------
- import_tasks: reverse_engineering.yml

#-------------------------------------------------------------------
# Burp Suite
#-------------------------------------------------------------------
- import_tasks: burp.yml
  tags:
    - gui
  when: hacker__install_burp
