---
- name: Create tools and tools/bin directories
  file:
    state: directory
    dest: "{{ hacker_tools_bin_dir }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

#-------------------------------------------------------------------
# Common
#-------------------------------------------------------------------
- name: Install Hacker "Common" packages
  become: yes
  apt:
    state: present
    name: "{{ hacker_packages_common }}"
  tags: hacker_common

#-------------------------------------------------------------------
# Tools
#-------------------------------------------------------------------
- name: Install Hacker "Tools"
  tags: hacker_tools
  block:

  - name: Install Hacker "Tools" packages
    become: yes
    apt:
      state: present
      name: "{{ hacker_packages_tools }}"

  - name: Install Hacker "Tools" Snaps
    become: yes
    snap:
      state: present
      name: "{{ hacker_snaps_tools }}"


#-------------------------------------------------------------------
# Wordlists / Data
#-------------------------------------------------------------------
- name: Install "SecLists"
  tags: hacker_seclists
  git:
    repo: 'https://github.com/danielmiessler/SecLists.git'
    version: '2021.2'
    dest: "{{ hacker_tools_dir }}/SecLists"


#-------------------------------------------------------------------
# Pentest
#-------------------------------------------------------------------
- name: Install Hacker "Pentest" tools
  tags: hacker_pentest
  block:

  - name: Install Hacker "Pentest" packages
    become: yes
    apt:
      state: present
      name: "{{ hacker_packages_pentest }}"

  - name: Install Hacker "Pentest" Snaps
    become: yes
    snap:
      state: present
      name: "{{ hacker_snaps_pentest }}"

  - name: Install metasploit via their omnibus installer
    shell: |
      curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > /tmp/msfinstall && \
      chmod 755 /tmp/msfinstall && \
      /tmp/msfinstall
    args:
      creates: /usr/bin/msfconsole

  - name: Download exploitdb project w/ searchsploit tools
    git:
      repo: 'https://github.com/offensive-security/exploitdb.git'
      version: '2021-06-19'
      dest: "{{ hacker_tools_dir }}/exploitdb"

  - name: Symlink searchsploit into PATH from exploitdb project
    become: yes
    file:
      state: link
      src: "{{ hacker_tools_dir }}/exploitdb/searchsploit"
      dest: "{{ hacker_tools_bin_dir }}/searchsploit"

#-------------------------------------------------------------------
# MISC
#-------------------------------------------------------------------
# - name: Install Hacker "Forensics" packages
#   become: yes
#   apt:
#     state: present
#     name: "{{ hacker_packages_forensics }}"
#   tags:
#     - hacker_forensics

# - name: Install Hacker "Reverse Engineering" packages
#   become: yes
#   apt:
#     state: present
#     name: "{{ hacker_packages_reverse_engr }}"
#   tags:
#     - hacker_reverse_eng

#-------------------------------------------------------------------
# Burp Suite
#-------------------------------------------------------------------
- import_tasks: burp.yml
  tags:
    - burp
  when: hacker_install_burp

