---
#-------------------------------------------------------------------
# Common
#-------------------------------------------------------------------
- name: Install Hacker "Common" packages
  become: yes
  apt:
    state: present
    name: "{{ hacker_packages_common }}"
  tags:
    - hacker_common

#-------------------------------------------------------------------
# Tools
#-------------------------------------------------------------------
- name: Install Hacker "Tools" packages
  become: yes
  apt:
    state: present
    name: "{{ hacker_packages_tools }}"
  tags:
    - hacker_tools

- name: Install Hacker "Tools" Snaps
  become: yes
  snap:
    state: present
    name: "{{ hacker_snaps_tools }}"
  tags:
    - hacker_tools

#-------------------------------------------------------------------
# Pentest
#-------------------------------------------------------------------
- name: Install Hacker "Pentest" packages
  become: yes
  apt:
    state: present
    name: "{{ hacker_packages_pentest }}"
  tags:
    - hacker_pentest

- name: Install Hacker "Pentest" Snaps
  become: yes
  snap:
    state: present
    name: "{{ hacker_snaps_pentest }}"
  tags:
    - hacker_pentest

#-------------------------------------------------------------------
# MISC
#-------------------------------------------------------------------
# - name: Install Hacker "Forensics" packages
#   become: yes
#   apt:
#     state: present
#     name: "{{ hacker_packages_forensics }}"
#   tags:
#     - hacker_forensics

# - name: Install Hacker "Reverse Engineering" packages
#   become: yes
#   apt:
#     state: present
#     name: "{{ hacker_packages_reverse_engr }}"
#   tags:
#     - hacker_reverse_eng

#-------------------------------------------------------------------
# Burp Suite
#-------------------------------------------------------------------
- import_tasks: burp.yml
  tags:
    - burp
  when: hacker_install_burp

