- name: hacker | ZAP | Download OWASP ZAP installer
  ansible.builtin.get_url:
    url: "{{ hacker__zap_installer_url }}"
    dest: "{{ downloads_dir }}/{{ hacker__zap_installer_filename }}"
    checksum: "{{ hacker__zap_installer_checksum }}"
    mode: '0755'

- name: hacker | ZAP | Lay down temp varfile to be used by install4j installer
  template:
    src: zap-install4j-response.varfile.j2
    dest: /tmp/zap-install4j-response.varfile

# ZAP uses the install4j installer tool (like Burp); see here for CLI args:
#   https://www.ej-technologies.com/resources/install4j/help/doc/installers/options.html
- name: hacker | ZAP | Run un-attended OWASP ZAP installer script
  become: yes
  shell: |
    {{ downloads_dir }}/{{ hacker__zap_installer_filename }} -q \
      -varfile /tmp/zap-install4j-response.varfile \
      -Dinstall4j.keepLog=true
  args:
    creates: "{{ hacker__zap_install_dir }}/zap.sh"  # symlinked into {{ hacker__zap_install_symlink_dir }}

- name: hacker | ZAP | Clean-up .desktop files & create .desktop file with nice icon
  become: yes
  shell: |
    rm -f /usr/share/applications/install4j_*-zap.sh.desktop \
    && \
    cat {{ hacker__zap_install_dir }}/.install4j/*.desktop \
      {{ hacker__zap_install_dir }}/OWASP\ ZAP.desktop \
      > /usr/share/applications/zaproxy.desktop
  args:
    creates: /usr/share/applications/zaproxy.desktop
