# ------------------------------------------------------------------------------
# This install is based off of:
#  - https://github.com/zsa/wally/wiki/Linux-install
# ------------------------------------------------------------------------------
- become: yes
  become_user: root
  when: is_gui | bool
  block:
    - name: moonlander | Install `wally` GUI dependencies
      ansible.builtin.apt:
        state: present
        name:
          # - gtk3
          # - libusb
          - libusb-1.0-0-dev
          # - webkit2gtk

    - name: moonlander | Create udev rules for ZSA moonlander keyboard
      ansible.builtin.template:
        src: 50-zsa-moonlander.rules.j2
        dest: /etc/udev/rules.d/50-zsa-moonlander.rules

    - name: moonlander | Install `wally` GUI application executable
      ansible.builtin.get_url:
        url: "{{ moonlander__wally_bin_url }}"
        dest: /usr/local/bin/wally
        mode: '0755'

    - name: moonlander | Install `wally` GUI application .desktop file
      ansible.builtin.get_url:
        url: "{{ moonlander__wally_desktop_url }}"
        dest: /usr/share/applications/wally-zsa-moonlander.desktop
        mode: '0644'

    # Can't seem to get icon location to work but don't have time to figure it out
    - name: moonlander | Install `wally` GUI application icon
      ansible.builtin.get_url:
        url: "{{ moonlander__wally_icon_url }}"
        # dest: /usr/share/icons/hicolor/256x256/apps/wally.png
        dest: /usr/share/icons/hicolor/128x128/apps/wally.png
        mode: '0644'
