---
# TODO: complete this dependency chain properly
dependencies: []
  # Relies on base__* variables
  #- role: base
  # This role requires `downloads_srv_dir` be created on host already
  #- role: dir_setup
