---
#-------------------------------------------------------------------------------
# HOW TO USE:
#
# - name: Install remote .debs
#   include_role:
#     name: packages
#     tasks_from: install_remote_deb.yml
#   vars:
#     pkg_deb_name: "{{ item.name }}"
#     pkg_deb_url: "{{ item.url }}"
#     pkg_deb_filename: "{{ item.filename }}"
#     pkg_deb_checksum: "{{ item.checksum | default('') }}"
#   loop: "{{ LIST_OF_REMOTE_DEBS }}"
#
#-------------------------------------------------------------------------------
- name: Download .deb file w/ checksum ({{ pkg_deb_name }})
  ansible.builtin.get_url:
    url: "{{ pkg_deb_url }}"
    dest: "{{ common__downloads_dir }}/{{ pkg_deb_filename }}"
    checksum: "{{ pkg_deb_checksum }}"
  when: pkg_deb_checksum is defined and pkg_deb_checksum != ""

- name: Download .deb file w/o checksum ({{ pkg_deb_name }})
  ansible.builtin.get_url:
    url: "{{ pkg_deb_url }}"
    dest: "{{ common__downloads_dir }}/{{ pkg_deb_filename }}"
  when: pkg_deb_checksum is not defined or pkg_deb_checksum == ""

- name: Install package via .deb ({{ pkg_deb_name }})
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    deb: "{{ common__downloads_dir }}/{{ pkg_deb_filename }}"
