---
- name: Clone `rbenv` repository
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "{{ ruby_rbenv_dir }}"
    version: "{{ ruby_rbenv_version }}"

- name: Compile dynamic Bash extension to speed up `rbenv`
  shell: cd {{ ruby_rbenv_dir }} && src/configure && make -C src
  args:
    creates: "{{ ruby_rbenv_dir }}/src/realpath.o"

- name: Install `rbenv-build` as `rbenv` plugin
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: "{{ ruby_rbenv_dir }}/plugins/ruby-build"
    version: "{{ ruby_ruby_build_version }}"

