---
tools_common_gui__packages:
  - parcellite
  - remmina
  # Logitech Unifying Rx tool (CLI & GUI)
  - solaar
  - synapse
  - usb-creator-gtk
  # In oreder to get +clipboard support
  - vim-gtk3
  - xclip
  - wireshark
tools_common_gui__gnome_shell_packages:
  - gnome-shell-pomodoro
tools_common_gui__remote_debs:
  - name: microsoft-teams
    url: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.10453_amd64.deb
    filename: teams_1.5.00.10453_amd64.deb
  - name: teamviewer
    url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    filename: teamviewer_amd64.deb
  - name: zoom
    url: https://zoom.us/client/latest/zoom_amd64.deb
    filename: zoom_amd64.deb
