---
#-------------------------------------------------------------------------------
# Vagrant
#-------------------------------------------------------------------------------
- name: Download Vagrant .deb SHA-256 checksum
  shell: |
    curl -s https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_SHA256SUMS \
      | grep vagrant_2.2.9_x86_64.deb \
      | cut -d ' ' -f 1
  args:
    warn: no
  register: vagrant_deb_sha256_task

- name: Download Vagrant .deb
  get_url:
    url: https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
    dest: "{{ downloads_srv_dir }}/vagrant_2.2.9_x86_64.deb"
    checksum: sha256:{{ vagrant_deb_sha256_task.stdout }}

- name: Install Vagrant via .deb
  become: yes
  apt:
    state: present
    deb: "{{ downloads_srv_dir }}/vagrant_2.2.9_x86_64.deb"

#--------------------------------------------------------------
# Vagrant's libvirt provider
# From: https://github.com/vagrant-libvirt/vagrant-libvirt#installation
#--------------------------------------------------------------
#- name: Install Vagrant libvirt provider build-dep dependencies
  #become: yes
  #apt:
    #state: build-dep
    #name: "{{ item }}"
  #with_items:
    #- ruby-libvirt

#- name: Install Vagrant libvirt provider dependencies
  #become: yes
  #apt:
    #state: present
    #name: "{{ item }}"
  #with_items:
    #- dnsmasq-base
    #- ebtables
    #- libxslt-dev
    #- libxml2-dev
    #- libvirt-dev
    #- ruby-dev
    #- zlib1g-dev

#-------------------------------------------------------------------------------
# Virtualbox - Virtualbox provider works out of box with Vagrant
#-------------------------------------------------------------------------------
- name: Download Oracle VirtualBox .deb SHA-256 checksum
  shell: |
    curl -s "{{ virtualbox_hash_url }}" \
      | grep "{{ virtualbox_deb_file }}" \
      | cut -d ' ' -f 1
  args:
    warn: no
  register: virtualbox_deb_sha256_task

- name: Download Oracle VirtualBox .deb
  get_url:
    url: "{{ virtualbox_deb_url }}"
    dest: "{{ downloads_srv_dir }}/{{ virtualbox_deb_file }}"
    checksum: sha256:{{ virtualbox_deb_sha256_task.stdout }}

- name: Install Oracle VirtualBox via .deb
  become: yes
  apt:
    state: present
    deb: "{{ downloads_srv_dir }}/{{ virtualbox_deb_file }}"

- name: Add "{{ username }}" to 'vboxusers' group
  become: yes
  user:
    state: present
    name: "{{ username }}"
    append: yes
    groups:
      - vboxusers

#-------------------------------------------------------------------------------
# Multipass
#-------------------------------------------------------------------------------
- name: Install Multipass Ubuntu VM manager by Canonical
  become: yes
  snap:
    state: present
    name: multipass
    classic: yes
  when: virtual_machines_install_multipass

#-------------------------------------------------------------------------------
# VMware-related
#-------------------------------------------------------------------------------
# Download requires website login, EULA acceptance, etc.; so is a real pain
# Thus, this requires a download of both bundle & its checksum file *outside of Ansible*
# to the same directory
- name: Verify checksum on Pre-Downloaded VMware ovftool installer
  shell: shasum -a 256 -c VMware-ovftool-4.4.0-16360108-lin.x86_64.bundle.shasum
  changed_when: False
  args:
    chdir: "{{ downloads_srv_dir }}"

- name: Run VMware ovftool installer
  become: yes
  shell: |
    ./VMware-ovftool-4.4.0-16360108-lin.x86_64.bundle \
      --console \
      --required \
      --eulas-agreed
  args:
    chdir: "{{ downloads_srv_dir }}"
    creates: /usr/bin/ovftool

