---
#--------------------------------------------------------------
# Vagrant's libvirt provider
# From: https://github.com/vagrant-libvirt/vagrant-libvirt#installation
#--------------------------------------------------------------
- name: Install Vagrant libvirt provider build-dep dependencies
  become: yes
  apt:
    state: build-dep
    name: "{{ item }}"
  with_items:
    - ruby-libvirt
  tags:
    - install
    - vagrant_libvirt

- name: Install Vagrant libvirt provider dependencies
  become: yes
  apt:
    state: present
    name: "{{ item }}"
  with_items:
    - dnsmasq-base
    - ebtables
    - libxslt-dev
    - libxml2-dev
    - libvirt-dev
    - ruby-dev
    - zlib1g-dev
  tags:
    - install
    - vagrant_libvirt

#-------------------------------------------------------------------------------
# Virtualbox - Virtualbox provider works out of box with Vagrant
#-------------------------------------------------------------------------------
- name: Install Oracle VirtualBox
  become: yes
  apt:
    state: present
    name: virtualbox
  tags:
    - install
    - virtualbox

- name: Add "{{ username }}" to 'vboxusers' group
  become: yes
  user:
    state: present
    name: "{{ username }}"
    append: yes
    groups:
      - vboxusers
  tags:
    - install
    # - virtualbox

#-------------------------------------------------------------------------------
# Multipass
#-------------------------------------------------------------------------------
- name: Install Multipass Ubuntu VM manager by Canonical
  become: yes
  snap:
    state: present
    name: multipass
    classic: yes
  when: virtual_machines__install_multipass
  tags:
    - install
    - multipass

#-------------------------------------------------------------------------------
# VMware-related
#-------------------------------------------------------------------------------
# Download requires website login, EULA acceptance, etc.; so is a real pain.
# Thus, this requires a download of both bundle & its checksum file *outside of Ansible*
# to the same directory
- name: Check if VMware ovftool has been downloaded outside of Ansible
  ansible.builtin.shell: |
    ls {{ virtual_machines__vmware_ovftool_installer }}
  changed_when: False
  ignore_errors: yes
  register: vmware_ovftool_installer_downloaded_check
  tags:
    - vmware

- name: Verify checksum on Pre-Downloaded VMware ovftool installer
  shell: shasum -a 256 -c {{ virtual_machines__vmware_ovftool_installer }}.sha256sum
  changed_when: False
  args:
    chdir: "{{ common__downloads_dir }}"
  when: vmware_ovftool_installer_downloaded_check.rc == 0
  tags:
    - vmware

- name: Run VMware ovftool installer
  become: yes
  shell: |
    {{ virtual_machines__vmware_ovftool_installer }} \
      --console \
      --required \
      --eulas-agreed
  args:
    creates: /usr/bin/ovftool
  when: vmware_ovftool_installer_downloaded_check.rc == 0
  tags:
    - install
    - vmware
