common_packages:
  - ack-grep
  - bzip2
  - curl
  - fd-find
  - fzf
  - git
  - gzip
  - htop
  - jq
  - pass
  - p7zip-full
  - ripgrep
  - silversearcher-ag
  - tmux
  - tree
  - universal-ctags
  - vim
  - wget
  - xz-utils
