---
- name: Disable system-resolved
  become: yes
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

# NOTE: NM updates resolv.conf everytime the network connection changes, which
# is why this is needed to deploy resolv.conf changes that persist even after
# network connections changes OR reboots
- name: Disable NetworkManager DNS so it won't overwrite /etc/resolv.conf
  ini_file:
    state: present
    path: /etc/NetworkManager/NetworkManager.conf
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644

- name: Replace resolv.conf that was managed by system-resolved/NetworkManager
  become: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
    backup: yes

