- name: Install Slack remote .deb
  include_tasks:
    file: global__install_remote_deb.yml
  loop:
    - name: slack
      url: https://downloads.slack-edge.com/releases/linux/4.23.0/prod/x64/slack-desktop-4.23.0-amd64.deb
      filename: slack-desktop-4.23.0-amd64.deb
  tags:
    - install
    - slack
    - remote_debs
