---
- name: dnsmasq-enable-restart
  become: yes
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: powerdns-enable-restart
  become: yes
  service:
    name: pdns
    state: restarted
    enabled: yes

