# TODO: clean-up this role and put vars into defaults
- name: zoom | Install from remote .deb
  include_tasks:
    file: global__install_remote_deb.yml
  loop:
    - name: zoom
      url: https://zoom.us/client/latest/zoom_amd64.deb
      filename: zoom_amd64.deb
  tags:
    - install
    - zoom
    - remote_debs
  when: is_gui | bool
