#-------------------------------------------------------------------------------
# http APT setup required before install packages task below
#-------------------------------------------------------------------------------
- name: devtools | Install httpie APT signing key
  become: yes
  become_user: root
  ansible.builtin.apt_key:
    state: present
    url: https://packages.httpie.io/deb/KEY.gpg
    keyring: /etc/apt/trusted.gpg.d/httpie.gpg
  tags:
    - setup
    - devtools
    - httpie
    - packages

- name: devtools | Install httpie APT repo
  become: yes
  become_user: root
  ansible.builtin.apt_repository:
    state: present
    repo: deb https://packages.httpie.io/deb ./
    filename: httpie
    update_cache: yes
  tags:
    - setup
    - devtools
    - httpie
    - packages
#-------------------------------------------------------------------------------

- name: devtools | Install devtools utility packages (minimal)
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ devtools__packages }}"
    state: present
  tags:
    - install
    - devtools
    - packages

- name: devtools | Install devtools utility packages (full)
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ devtools__packages_full }}"
    state: present
  tags:
    - install
    - devtools
    - packages
    - full
  when: install_type == "full"

- name: devtools | Install devtools utilities from remote .debs
  include_tasks:
    file: global__install_remote_deb.yml
  loop: "{{ devtools__remote_debs }}"
  tags:
    - install
    - devtools
    - remote_debs

- name: devtools | Install devtools utilities from remote archives
  include_tasks:
    file: global__install_remote_archive.yml
  loop: "{{ devtools__remote_archives }}"
  tags:
    - install
    - devtools
    - remote_archives
