---
- name: Install Docker's APT repository key
  become: yes
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker's APT repository for Ubuntu 18.04
  become: yes
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "18"

- name: Add Docker's APT repository for Ubuntu 20.04
  become: yes
  apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "20"

- name: Install Docker from Docker's Ubuntu package repo
  become: yes
  apt:
    state: present
    name: "{{ docker_packages }}"
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create 'docker' group
  become: yes
  group:
    state: present
    name: docker
    system: yes

- name: Add users to 'docker' group so they can run Docker commands w/o sudo
  become: yes
  user:
    state: present
    name: "{{ item }}"
    append: yes
    groups:
      - docker
  loop: "{{ docker_docker_users }}"

- name: Enable Docker service to run on startup
  become: yes
  service:
    name: docker
    enabled: yes
