---
#-------------------------------------------------------------------------------
# SEE: https://kifarunix.com/configure-local-dns-server-using-dnsmasq-on-ubuntu-20-04/
#-------------------------------------------------------------------------------
- name: Install dnsmasq from APT
  become: yes
  apt:
    name: dnsmasq
    state: present

- name: Setup initial /etc/dnsmasq.conf
  become: yes
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - dnsmasq-enable-restart

