- name: docker | Install Docker's APT repository key
  become: yes
  become_user: root
  ansible.builtin.apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - install
    - setup
    - docker

- name: docker | Add Docker's APT repository for Ubuntu 18.04
  become: yes
  become_user: root
  ansible.builtin.apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "18"
  tags:
    - install
    - setup
    - docker

- name: docker | Add Docker's APT repository for Ubuntu 20.04
  become: yes
  become_user: root
  ansible.builtin.apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "20"
  tags:
    - install
    - setup
    - docker

- name: docker | Add Docker's APT repository for Ubuntu 22.04
  become: yes
  become_user: root
  ansible.builtin.apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    update_cache: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "22"
  tags:
    - install
    - setup
    - docker

- name: docker | Install Docker from Docker's Ubuntu package repo
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: "{{ docker_packages }}"
  vars:
    docker_packages:
      - containerd.io
      - docker-ce
      - docker-ce-cli
  tags:
    - install
    - setup
    - docker

- name: docker | Install Docker Compose Plugin from Docker's Ubuntu package repo
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: docker-compose-plugin
  tags:
    - install
    - docker

- name: docker | Create 'docker' group
  become: yes
  become_user: root
  ansible.builtin.group:
    state: present
    name: docker
    system: yes
  tags:
    - install
    - setup
    - docker

- name: docker | Add users to 'docker' group so they can run Docker commands w/o sudo
  become: yes
  become_user: root
  ansible.builtin.user:
    state: present
    name: "{{ item }}"
    append: yes
    groups:
      - docker
  loop: "{{ docker__docker_users }}"
  tags:
    - install
    - setup
    - docker

- name: docker | Enable Docker service to run on startup
  become: yes
  become_user: root
  ansible.builtin.service:
    name: docker
    enabled: yes
  tags:
    - install
    - docker
