---
- name: Install QEMU emulator for KVM hypervisor
  become: yes
  apt:
    state: present
    name: qemu-kvm

- name: Install 'libvirtd' daemon for managing VMs
  become: yes
  apt:
    state: present
    name: libvirt-daemon-system

- name: Ensure 'libvirtd' service is enabled and running
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Install libvirt client tools
  become: yes
  apt:
    state: present
    name: libvirt-clients

- name: Install 'virt-manager' GUI for managing VMs
  become: yes
  apt:
    state: present
    name: virt-manager

- name: Install 'virt-viewer' utility for viewing graphical console of VMs
  become: yes
  apt:
    state: present
    name: virt-viewer

- name: Install 'virt-list-filesystems' utility for viewing vdisk filesystems
  become: yes
  apt:
    state: present
    name: libguestfs-tools

- name: Install 'bridge-utils' for creating Linux Ethernet bridges
  become: yes
  apt:
    state: present
    name: bridge-utils

- name: Install 'osinfo-query' tool for querying osinfo DB
  become: yes
  apt:
    state: present
    name: libosinfo-bin
