---
- name: Install common utility packages
  become: yes
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install common tools via remote .debs
  include_role:
    name: packages
    tasks_from: install_remote_deb.yml
  vars:
    pkg_deb_name: "{{ item.name }}"
    pkg_deb_url: "{{ item.url }}"
    pkg_deb_filename: "{{ item.filename }}"
    pkg_deb_checksum: "{{ item.checksum | default('') }}"
  loop: "{{ common_remote_debs }}"
