- name: tools_common | Install common utility packages
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ tools_common__packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - install
    - tools_common
    - packages

- name: tools_common | Install common tools from remote .debs
  include_tasks:
    file: global__install_remote_deb.yml
  loop: "{{ tools_common__remote_debs }}"
  tags:
    - install
    - tools_common
    - remote_debs

- name: tools_common | Install common tools from remote archives
  include_tasks:
    file: global__install_remote_archive.yml
  loop: "{{ tools_common__remote_archives }}"
  tags:
    - install
    - tools_common
    - remote_archives

- name: tools_common | Install common packages for Desktop enivronments (gui)
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ tools_common__gui_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: is_gui
  tags:
    - install
    - tools_common
    - packages

- name: tools_common | Install common tools for Desktop enivronments from remote .debs (gui)
  include_tasks:
    file: global__install_remote_deb.yml
  loop: "{{ tools_common__gui_remote_debs }}"
  when: is_gui
  tags:
    - install
    - tools_common
    - remote_debs

# This won't work with 'ansible.builtin.shell' for some reason??
- name: tools_common | Determine if gnome-shell is installed (gui)
  shell: |
    dpkg -l | grep '^ii  gnome-shell '
  changed_when: False
  ignore_errors: yes
  register: is_gnome_shell_installed
  when: is_gui

- name: tools_common | Install Gnome Shell-related packages (gui)
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ tools_common__gui_gnome_shell_packages }}"
    state: present
  when: is_gui and is_gnome_shell_installed.rc == 0
