#-------------------------------------------------------------------------------
# For info on "color profile" and "system crash" issues when connecting to the
# Xrdp server for the first time:
#
#   - https://c-nergy.be/blog/?p=12073
#   - http://c-nergy.be/blog/?p=12043
#-------------------------------------------------------------------------------
- name: xrdp | Install Xrdp server for RDP connections
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name: xrdp

- name: xrdp | Ensure xrdp service is running and enabled
  become: yes
  become_user: root
  ansible.builtin.service:
    state: started
    name: xrdp
    enabled: yes
