---
- name: Make directory for CNI reference plugin binaries
  become: yes
  file:
    state: directory
    dest: /opt/cni/bin
    owner: root
    group: root
    mode: '0755'

- name: Download & install CNI reference plugins
  become: yes
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
    dest: /opt/cni/bin
    remote_src: yes
    creates: /opt/cni/bin/bridge

- name: Setup default loopback configuration
  become: yes
  copy:
    src: 99-loopback.conf
    dest: /etc/cni/net.d/99-loopback.conf
    owner: root
    group: root
    mode: '0644'
  notify: kubelet_restart
