# TODO: clean-up this role and put vars into defaults
- name: teamviewer | Install from remote .deb
  include_tasks:
    file: global__install_remote_deb.yml
  loop:
    - name: teamviewer
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      filename: teamviewer_amd64.deb
  tags:
    - install
    - teamviewer
    - remote_debs
