# TODO: clean-up this role and put vars into defaults
- name: teamviewer | Install from remote .deb
  include_role:
    name: packages
    tasks_from: install_remote_deb.yml
  vars:
    pkg_deb_name: "{{ item.name }}"
    pkg_deb_url: "{{ item.url }}"
    pkg_deb_filename: "{{ item.filename }}"
    pkg_deb_checksum: "{{ item.checksum | default('') }}"
  loop:
    - name: teamviewer
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      filename: teamviewer_amd64.deb
  tags:
    - teamviewer
    - remote_archives
