- name: base | Install base utility packages
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ base__packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - base
    - install
    - packages

- name: base | Install base tools from remote .debs
  include_tasks:
    file: global__install_remote_deb.yml
  loop: "{{ base__remote_debs }}"
  tags:
    - base
    - install
    - remote_debs

- name: base | Install base tools from remote archives
  include_tasks:
    file: global__install_remote_archive
  loop: "{{ base__remote_archives }}"
  tags:
    - base
    - install
    - remote_archives

- name: base | Install base modern utility packages
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: "{{ base__packages_modern }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - base
    - install
    - packages

- name: base | Install base modern tools from remote .debs
  include_tasks:
    file: global__install_remote_deb.yml
  loop: "{{ base__remote_debs_modern }}"
  tags:
    - base
    - install
    - remote_debs

- name: base | Install base modern tools from remote archives
  include_tasks:
    file: global__install_remote_archive
  loop: "{{ base__remote_archives_modern }}"
  tags:
    - base
    - install
    - remote_archives
