---
- name: Build 'docker-compose' URL
  shell: |
    echo "https://github.com/docker/compose/releases/download/{{ docker_compose__version }}/docker-compose-$(uname -s)-$(uname -m)"
  register: docker_compose_url
  changed_when: False

- name: Download & install 'docker-compose'
  become: yes
  get_url:
    url: "{{ docker_compose_url.stdout }}"
    dest: /usr/local/bin/docker-compose
    mode: "ugo+x"

- name: Download & install 'docker-compose' Bash completion
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose__version }}/contrib/completion/bash/docker-compose
    dest: "/etc/bash_completion.d/docker-compose"
