---
- name: Install Debian dependencies
  become: yes
  become_user: root
  ansible.builtin.apt:
    state: present
    name:
      - cmake
      - libxcb-xfixes0-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxkbcommon-dev
      - pkg-config
      - python3

- name: Checkout alacritty git repository
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty.git'
    dest: "{{ common__git_dir }}/alacritty"

- name: Build alacritty from source
  shell: |
    "{{ ansible_env.HOME }}"/.cargo/bin/cargo build --release
  args:
    chdir: "{{ common__git_dir }}/alacritty"
    creates: "{{ common__git_dir }}/alacritty/target/release/alacritty"

- name: Copy alacritty binary to ansible bin directory
  copy:
    src: "{{ common__git_dir }}/alacritty/target/release/alacritty"
    dest: "{{ common__bin_dir }}/alacritty"
    mode: 0755

- name: Symlink alacritty binary to /usr/local/bin
  become: yes
  become_user: root
  file:
    state: link
    src: "{{ common__bin_dir }}/alacritty"
    dest: /usr/local/bin/alacritty
    owner: root
    group: root
    mode: 0755

- name: Copy alacritty logo to /usr/share/pixmaps for use with .desktop file
  become: yes
  become_user: root
  copy:
    src: "{{ common__git_dir }}/alacritty/extra/logo/alacritty-term.svg"
    dest: /usr/share/pixmaps/Alacritty.svg
    owner: root
    group: root

- name: Install alacritty .desktop file
  become: yes
  become_user: root
  shell: |
    desktop-file-install {{ common__git_dir }}/alacritty/extra/linux/Alacritty.desktop
    update-desktop-database
  changed_when: False

