- name: openvpn | Install OpenVPN Client/Server
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: openvpn
    state: present
  tags:
    - install
    - openvpn

- name: openvpn | Install Easy-RSA
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: easy-rsa
    state: present
  tags:
    - install
    - openvpn

# For some reason, the easy-rsa package does not put the `easyrsa` in a common bin directory
- name: openvpn | Symlink Easy-RSA executable into common PATH location
  become: yes
  become_user: root
  ansible.builtin.file:
    state: link
    src: "{{ openvpn__easyrsa_bin }}"
    dest: "{{ openvpn__easyrsa_bin_symlink }}"
  tags:
    - install
    - openvpn

# TODO: the imported tasks are quite old & are meant to configure an OpenVPN SERVER;
# they probably need to be re-visited
- import_tasks: setup_vpn_server.yml
  when: False
