- name: openvpn | Create Easy-RSA PKI folder in home directory
  ansible.builtin.file:
    path: "{{ openvpn__easyrsa_dir }}"
    state: directory
    mode: '0700'

- name: openvpn | Symlink Easy-RSA package files to Easy-RSA PKI folder
  shell: |
    ln -s /usr/share/easy-rsa/* {{ openvpn__easyrsa_dir }}/
  args:
    creates: "{{ openvpn__easyrsa_dir }}/easyrsa"

- name: openvpn | Initialize the Easy-RSA PKI
  shell: |
    ./easyrsa init-pki
  args:
    chdir: "{{ openvpn__easyrsa_dir }}"
    creates: "{{ openvpn__easyrsa_dir }}/pki"

- name: openvpn | Create 'vars' file for use in creating CA
  ansible.builtin.copy:
    src: vars
    dest: "{{ openvpn__easyrsa_dir }}/vars"

# The 'echo' simulates hitting enter on interactive 'gen-req'; this is needed to
# ensure CN on CSR is not 'ChangeMe' and is the server name provided to command
- name: openvpn | Create CA certificate request
  shell: |
    echo | ./easyrsa gen-req {{ openvpn__server_name }} nopass
  args:
    chdir: "{{ openvpn__easyrsa_dir }}"
    creates: "{{ openvpn__easyrsa_dir }}/pki/reqs/{{ openvpn__server_name }}.req"

- name: openvpn | Make server.key file read-only to help prevent deletion
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0400'
  loop:
    - "{{ openvpn__easyrsa_dir }}/pki/private/{{ openvpn__server_name }}.key"

- name: openvpn | Copy server.key to OpenVPN config directory
  become: yes
  become_user: root
  ansible.builtin.copy:
    src: "{{ openvpn__easyrsa_dir }}/pki/private/{{ openvpn__server_name }}.key"
    dest: /etc/openvpn/server/
    remote_src: yes

- name: openvpn | Fetch server.req certificate request for signing by CA on local machine
  ansible.builtin.fetch:
    src: "{{ openvpn__easyrsa_dir }}/pki/reqs/{{ openvpn__server_name }}.req"
    dest: ~/easy-rsa/pki/reqs/{{ openvpn__server_name }}.req
    flat: yes

- name: openvpn | Sign CSR by CA on local machine to create server certificate
  delegate_to: localhost
  shell: |
    ./easyrsa sign-req server {{ openvpn__server_name }}
  args:
    chdir: ~/easy-rsa
    creates: ~/easy-rsa/pki/issued/{{ openvpn__server_name }}.crt
  environment:
    EASYRSA_BATCH: 1

- name: openvpn | Copy issued server certificate and ca.crt back to OpenVPN server
  become: yes
  become_user: root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/openvpn/server/
  loop:
    - ~/easy-rsa/pki/issued/{{ openvpn__server_name }}.crt
    - ~/easy-rsa/pki/ca.crt

- name: openvpn | Generate OpenVPN `tls-crypt` pre-shared key
  shell: |
    openvpn --genkey --secret ta.key
  args:
    chdir: "{{ openvpn__easyrsa_dir }}"
    creates: "{{ openvpn__easyrsa_dir }}/ta.key"

- name: openvpn | Copy generated `tls-crypt` pre-shard key to OpenVPN config directory
  become: yes
  become_user: root
  ansible.builtin.copy:
    src: "{{ openvpn__easyrsa_dir }}/ta.key"
    dest: /etc/openvpn/server/
    remote_src: yes
